### ISSUE TITLE
[Bug] Error setting up entry OMV for openmediavault

### ISSUE THREAD

**Issue by mv5903** [tomaae/homeassistant-openmediavault#101]
## Describe the issue
Hi, I am attempting to add the integration into my Home Assistant Instance

## How to reproduce the issue
1. Add the integration after installing via HACS
2. Fill in the information, using the same account I use to access the OMV instance from Windows, leaving all SSL options unchecked as I do not have that set up.

## Expected behavior
Expecting it to set up successfully, however, I am unable to get it working properly

## Screenshots
![integration](https://user-images.githubusercontent.com/39844660/224496054-afa4c2b8-7649-487f-afd2-aab3ca55c9c1.png)

## Software versions
 - Home Assistant version: 2023.3.3 (Running HAOS on HyperV with a unique IP address)
 - openmediavault integration version: v1.3.0
 - openmediavault software version: 6.0.24-1 (Running the OMV OS on HyperV with a unique IP address)

## Diagnostics data
N/A

## Traceback/Error logs
These are the only logs I am able to see on my end:

2023-03-11 11:33:24.648 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OMV for openmediavault
File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
File "/config/custom_components/openmediavault/omv_controller.py", line 132, in async_hwinfo_update
File "/config/custom_components/openmediavault/omv_controller.py", line 198, in get_hwinfo

## Additional context
OMV is a fresh install and I am able to access it just fine from my iOS and Windows devices natively. Home Assistant is also running just fine and is accessible locally and externally through my domain.

**Comment by tomaae** [comment]
probably related to #98
