### ISSUE TITLE
[Lokalise] Add new translations language

### ISSUE THREAD

**Issue by el97** [tomaae/homeassistant-openmediavault#102]
I can provide a Swedish translation.

**Comment by tomaae** [comment]
Language added

**Comment by el97** [comment]
I can see that you added the Swedish language when I to the join project page. but when I am on the page for available languages to translate Swedish isn't showing up.
![Skärmbild 2023-03-27 185435](https://user-images.githubusercontent.com/23169868/228011991-7364cf02-b5e4-4ef7-a1f8-a97e75b4e702.png)

**Comment by tomaae** [comment]
you have to add the language you want to see. I added it for you now

**Comment by BebeMischa** [comment]
Hallo, dear Tomaae,

I also wanted to spend some time on localizing your addon to Dutch, but on lokalize, I'm a member of your team, but I can't find the button to add a language.

I also can't see the Swedish language too.

As per manual, I have to do this:

![afbeelding](https://user-images.githubusercontent.com/73079275/228031773-919f8bde-9c8e-474a-87c5-1ce38f79cfab.png)

but in your project, all I can see is this, no add button, no Swedish to see:

![afbeelding](https://user-images.githubusercontent.com/73079275/228032057-fdb4ee5c-8ae9-45f6-b445-128b3653bd3f.png)


Maybe you need to set some rights for team members?

I would happily contribute to make this project even better, when I get allowed to ;-)

**Comment by tomaae** [comment]
sure, added dutch

**Comment by BebeMischa** [comment]
Done ;-)

**Comment by tomaae** [comment]
thanks ;)
