### ISSUE TITLE
No temperature value on NVME drive

### ISSUE THREAD

**Issue by BebeMischa** [tomaae/homeassistant-openmediavault#108]
## Describe the issue

Temperature of NVME drive "unknown

## How to reproduce the issue

1. Install NVME drive
2. Lookup available sensors

## Expected behavior

The temperature of an NVME drive will be displayed the same way, ass SATA drives

## Screenshots

![afbeelding](https://user-images.githubusercontent.com/73079275/233366507-f8bb8c17-6204-48af-8c40-35bebdbc379b.png)

## Software versions

All fields in this sections are required.

 - Home Assistant version:  Home Assistant 2023.4.5 Supervisor 2023.04.0 Frontend-versie: 20230411.1 - latest 
 - openmediavault integration version: 1.3.0 MASTER
 - openmediavault software version: 6.3.8-1 (Shaitan)

## Diagnostics data

  
[config_entry-openmediavault-98524fbac0980bbe729327fa06f337d1.json.txt](https://github.com/tomaae/homeassistant-openmediavault/files/11286233/config_entry-openmediavault-98524fbac0980bbe729327fa06f337d1.json.txt)

**Comment by tomaae** [comment]
Ah yea, nvme smart can be an issue. Can you try to debug it to see if it is even available via omv? Also, is nvme temperature visible in omv ui?

**Comment by BebeMischa** [comment]
Well, i can se the temp under SMART:

![afbeelding](https://user-images.githubusercontent.com/73079275/233392255-e34649c6-240c-4060-b6f3-15cbf2fba04a.png)

Will debug in the weekend time, to busy now ;-)

**Comment by tomaae** [comment]
sure, thanks :)

**Comment by tomaae** [comment]
yea, it is using different value names in smart. this should do it.

**Comment by BebeMischa** [comment]
Still gives 0 with 3542deb 

![afbeelding](https://user-images.githubusercontent.com/73079275/234434060-11096662-87a4-4703-b680-91acb0f0cc40.png)

**Comment by tomaae** [comment]
try now?

**Comment by BebeMischa** [comment]
ee07855

![afbeelding](https://user-images.githubusercontent.com/73079275/234435527-836b7d80-aaab-42fc-8d70-edf0f13fb7af.png)

**Comment by tomaae** [comment]
oh, I made a mistake. nvme actually does not respond with data
```
2023-04-25 20:39:48.025 DEBUG (SyncWorker_6) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.178.133 query: Smart, getAttributes, {'devicefile': '/dev/nvme0n1'}, {'updatelastaccess': False}
2023-04-25 20:39:48.096 DEBUG (SyncWorker_6) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.178.133 query response: {'response': [], 'error': None}
```

Lets try different approach.
Add smart to your dashboard and open inspector. Lookup for smart queries and lets see what kind of query and response we get for nvme.

Cant really give you exact example as smart wont work on VM, but this is close enough:
![image](https://user-images.githubusercontent.com/23486452/234811814-31209d9a-e784-4084-80d7-c3f20f750815.png)

**Comment by BebeMischa** [comment]
"Add smart to your dashboard"

How? (let me see, what is now covered by the inspector) ;-)

**Comment by tomaae** [comment]
I just added it like this:
![image](https://user-images.githubusercontent.com/23486452/234823382-35eff775-78ed-46aa-879a-dbc56d052f82.png)

**Comment by BebeMischa** [comment]
Looks, like that gives only this, so there is no temperature info in it, I have to click on the nvme drive to see the info.

![image](https://user-images.githubusercontent.com/73079275/234824568-9056fefc-4ac9-4cc9-8f0d-695f784741b4.png)

after click on nvme drive:

![image](https://user-images.githubusercontent.com/73079275/234824782-b3cffd91-46e7-41e6-88f9-a0dbc4036af1.png)

**Comment by BebeMischa** [comment]
```
{"response":{"devicefile":"\/dev\/nvme0n1","devicemodel":"SSSTC CL1-8D128-HP","serialnumber":"UJDJA01ZTDV489","wwn":"eui.38f6015630136112","firmwareversion":"L182","usercapacity":"","modelnumber":"SSSTC CL1-8D128-HP","pcivendorid":"0x1e95","pcivendorsubsystemid":"0x126f","ieeeouiidentifier":"0x38f601","totalnvmcapacity":"128,035,676,160 [128 GB]","unallocatednvmcapacity":"0","controllerid":"1","nvmeversion":"1.3","numberofnamespaces":"1","namespace1size\/capacity":"128,035,676,160 [128 GB]","namespace1formattedlbasize":"512","namespace1ieeeeui-64":"38f601 5630136112","localtimeis":"Thu Apr 27 12:10:47 2023 CEST","firmwareupdates(0x14)":"2 Slots, no Reset required","optionaladmincommands(0x0017)":"Security Format Frmw_DL Self_Test","optionalnvmcommands(0x001f)":"Comp Wr_Unc DS_Mngmt Wr_Zero Sav\/Sel_Feat","logpageattributes(0x07)":"S\/H_per_NS Cmd_Eff_Lg Ext_Get_Lg","maximumdatatransfersize":"64 Pages","warningcomp.temp.threshold":"84 Celsius","criticalcomp.temp.threshold":"85 Celsius","smartoverall-healthself-assessmenttestresult":"PASSED","criticalwarning":"0x00","temperature":"28","availablespare":"100%","availablesparethreshold":"5%","percentageused":"4%","dataunitsread":"1,770,735 [906 GB]","dataunitswritten":"3,169,343 [1.62 TB]","hostreadcommands":"28,036,584","hostwritecommands":"94,664,987","controllerbusytime":"1,176","powercycles":"76","poweronhours":"7,672","unsafeshutdowns":"42","mediaanddataintegrityerrors":"0","errorinformationlogentries":"0","warningcomp.temperaturetime":"0","criticalcomp.temperaturetime":"0","temperaturesensor1":"28 Celsius"},"error":null}
```

**Comment by tomaae** [comment]
can you try now?

**Comment by BebeMischa** [comment]
You are a fabulous winner! ;-)

![image](https://user-images.githubusercontent.com/73079275/234841888-c913ef94-1d4c-4bbd-b04c-df3610173baf.png)
