### ISSUE TITLE
Update sensor shows false unless there are updates available

### ISSUE THREAD

**Issue by BebeMischa** [tomaae/homeassistant-openmediavault#109]
## Describe the issue
There are updates available within OMV, but HA update sensor says FALSE

## How to reproduce the issue
Difficult to say, as you are running OMV virtually

## Expected behavior
OMV sensor in HA woud say TRUE, if there are updates available

## Screenshots
![afbeelding](https://user-images.githubusercontent.com/73079275/234377021-c542a849-1022-4b2a-a585-1f12d1470e33.png)
![afbeelding](https://user-images.githubusercontent.com/73079275/234377171-639b89d3-af63-47be-843c-555b203a9536.png)

## Software versions

 - Home Assistant 2023.4.6 Supervisor 2023.04.1 Frontend-versie: 20230411.1 - latest 
 - openmediavault integration version: v1.3.0 master
 - openmediavault software version:  6.3.8-1 (Shaitan) 

## Diagnostics data

[config_entry-openmediavault-98524fbac0980bbe729327fa06f337d1.json(1).txt](https://github.com/tomaae/homeassistant-openmediavault/files/11325956/config_entry-openmediavault-98524fbac0980bbe729327fa06f337d1.json.1.txt)

## Traceback/Error logs

[home-assistant_openmediavault_2023-04-25T18-48-46.282Z.log](https://github.com/tomaae/homeassistant-openmediavault/files/11325948/home-assistant_openmediavault_2023-04-25T18-48-46.282Z.log)

## Additional context
In the error log there is clearly stated, that there are 27 updates, the same amount, as can be seen on the OMV machine self.
So the info is correctly read by OMV integration, just the sensor does not change its state.

Thank you again for digging in to it ;-)

**Comment by tomaae** [comment]
Yes, integration correctly gets info from API and it should work for you. 
can you screenshot whole OMV System device like this?
![image](https://user-images.githubusercontent.com/23486452/234408775-35d940e0-3860-47f8-b8a6-277b7dcf7a7a.png)
Also make sure you dont have 2 of them under the integration.

**Comment by BebeMischa** [comment]
![afbeelding](https://user-images.githubusercontent.com/73079275/234409362-665bc26e-f571-403e-8444-e91ff34497fe.png)

![afbeelding](https://user-images.githubusercontent.com/73079275/234409568-329c1a73-c603-48f5-8dda-e8b0a61e2647.png)

![afbeelding](https://user-images.githubusercontent.com/73079275/234409648-1d3a0503-a249-4336-90f3-1e945f3c572e.png)

**Comment by tomaae** [comment]
this is not right. you are probably not on latest master. you should see network sensors.
Also KVM and compose if you are using them.
![image](https://user-images.githubusercontent.com/23486452/234409969-8685dfa0-19d2-4b61-a0ef-28b5ad990c02.png)

**Comment by BebeMischa** [comment]
I've selected re-download in HACS and there selected MASTER just today again, before all testing. Is it possible that this method does not get the latest?

I already noticed, that I also do not see the shutdown/restart services ;-)

**Comment by tomaae** [comment]
yea, something could be stuck there. maybe try to remove integration in hacs, make sure all files are gone and reinstall.

**Comment by BebeMischa** [comment]
Still ending up with 1.3.0 even when selecting master.

**Comment by tomaae** [comment]
weird, it should work

**Comment by tomaae** [comment]
you may always try to copy it from github

**Comment by BebeMischa** [comment]
third try (patient people always win) i got the master.

But with that version - 

OMV integration cannot be setup:

`Error setting up entry OMV for openmediavault

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openmediavault/__init__.py", line 30, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 183, in async_update
    await self.hass.async_add_executor_job(self.get_smart)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 386, in get_smart
    tmp_data = parse_api(
  File "/config/custom_components/openmediavault/apiparser.py", line 137, in parse_api
    data = fill_vals(data, entry, uid, vals)
  File "/config/custom_components/openmediavault/apiparser.py", line 269, in fill_vals
    data[uid][_name] = from_entry(entry, _source, default=_default)
  File "/config/custom_components/openmediavault/apiparser.py", line 43, in from_entry
    ret = int(ret)
ValueError: invalid literal for int() with base 10: '394 (Average 431)'
`

**Comment by tomaae** [comment]
try now

**Comment by BebeMischa** [comment]
e78254f

```
Error setting up entry OMV for openmediavault

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openmediavault/__init__.py", line 30, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 183, in async_update
    await self.hass.async_add_executor_job(self.get_smart)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 387, in get_smart
    tmp_data = parse_api(
  File "/config/custom_components/openmediavault/apiparser.py", line 137, in parse_api
    data = fill_vals(data, entry, uid, vals)
  File "/config/custom_components/openmediavault/apiparser.py", line 269, in fill_vals
    data[uid][_name] = from_entry(entry, _source, default=_default)
  File "/config/custom_components/openmediavault/apiparser.py", line 43, in from_entry
    ret = int(ret)
ValueError: invalid literal for int() with base 10: '394 (Average 431)'
```

**Comment by BebeMischa** [comment]
Could this be a problem? No closing sign?

![afbeelding](https://user-images.githubusercontent.com/73079275/234424561-db4dbe6f-55e5-48e0-9014-19f10c812209.png)

**Comment by tomaae** [comment]
no, thats not a problem. last line is the issue.

**Comment by tomaae** [comment]
ok, give it a try now

**Comment by tomaae** [comment]
added one more check so we dont run into issues with correct responses

**Comment by BebeMischa** [comment]
9f6c75d

still not better

**Comment by tomaae** [comment]
what do you get now?

**Comment by BebeMischa** [comment]
was the same, now going to try the new without CPU temp...

**Comment by tomaae** [comment]
nah, cpu temp does not matter there, it was my mistake

**Comment by BebeMischa** [comment]
3542deb

![afbeelding](https://user-images.githubusercontent.com/73079275/234431662-e68397cd-61ce-4a5e-b3c4-712e4aed76c0.png)

**Comment by tomaae** [comment]
looks good to me
beschikbaar is available, right?

**Comment by BebeMischa** [comment]
exactly

**Comment by BebeMischa** [comment]
lot of sensors changed name, so dashboard has to be reworked a bit, but that does not bother me... ;-)

**Comment by tomaae** [comment]
yea, I standardized lot of sensor names and some uuid for sensors changed because of new implementation

**Comment by BebeMischa** [comment]
Thank you again for all the love... ;-)

**Comment by BebeMischa** [comment]
Houston, we got a problem. The update thing is fixed, I even updated OMV now, to check, if the sensor changes state. Works fine.

But now CPU load and Memory sensors don't update...

![afbeelding](https://user-images.githubusercontent.com/73079275/234434823-dccd2e37-5640-46a3-b427-f3c39e8147a3.png)

![afbeelding](https://user-images.githubusercontent.com/73079275/234434881-91a1dacc-2ba4-42b5-a12d-b60a6c298c97.png)

**Comment by tomaae** [comment]
weird, check debug if it keeps updating every minute.

**Comment by BebeMischa** [comment]
[home-assistant_openmediavault_2023-04-26T00-26-40.951Z.log](https://github.com/tomaae/homeassistant-openmediavault/files/11327777/home-assistant_openmediavault_2023-04-26T00-26-40.951Z.log)

**Comment by BebeMischa** [comment]
The new RX/TX sensors also don't work, always 0.0

**Comment by tomaae** [comment]
yea, you really have low cpu usage. often sub 1%

**Comment by BebeMischa** [comment]
yeah, always between 1-13 %. But even with upating, it raised to 13 % in OMV dashboard, but no any change in HA.

After restart of HA it picked up 5 % and stays like that, even when OMV changes.

**Comment by BebeMischa** [comment]
![afbeelding](https://user-images.githubusercontent.com/73079275/234436667-6adc3c2e-092e-4a00-9cbf-7f99036ca9f0.png)

![afbeelding](https://user-images.githubusercontent.com/73079275/234436709-332d131e-d2f1-4bc9-92da-31f842e64035.png)

**Comment by BebeMischa** [comment]
going to try 23da0c1

**Comment by BebeMischa** [comment]
23da0c1

it still picks up a initial value after HA restart and never changes again.

I can't continue testing for now, have to go sleep, other ways tomorrow I will be a zombie ;-)

**Comment by tomaae** [comment]
yea, same. its too late.
attributes are updated, but main value is not. I will have to look deeper into this

**Comment by BebeMischa** [comment]
good night, nice working with you! ;-)

**Comment by tomaae** [comment]
fixed, also added new features for sensors like suggested unit of measurement and precision

**Comment by BebeMischa** [comment]
dcc8a9b

seems to run good.

here is a log for you, just to check for things, I would not see. ;-)

[home-assistant_openmediavault_2023-04-27T09-30-11.800Z.log](https://github.com/tomaae/homeassistant-openmediavault/files/11341907/home-assistant_openmediavault_2023-04-27T09-30-11.800Z.log)
