### ISSUE TITLE
[Bug] Devices without smart support causing issues

### ISSUE THREAD

**Issue by LanceMcCarthy** [tomaae/homeassistant-openmediavault#11]
## Describe the issue

After applying a recent update (1 or 2 versions ago as of writing this), all the entities are no longer reporting:

![image](https://user-images.githubusercontent.com/3520532/81736825-2d400700-9465-11ea-83e0-64a5dc17b953.png)

This of course breaks cards, for example:

![image](https://user-images.githubusercontent.com/3520532/81737323-f0c0db00-9465-11ea-9c96-de53d2d482db.png)

## How to reproduce the issue

In the above screenshot, those 4 broken cards are sensors are hard drive's used space values in a Gauge card.

## Expected behavior

existing entities stay intact after update.

## Software versions

 - Home Assistant version:  HA v0.109.6 (on HassOS 3.13)
 - openmediavault integration version: 1.1.0
 - openmediavault software version: 5.4.5-1 (Usul) [latest]

## Additional context

I am not deleting and re-adding the integration after updating the plugin. Is this required?

**Comment by LanceMcCarthy** [comment]
To add more context, I deleted the integration and re-added it.

I got the expected email from OMV that a user had signed in, which made me realize something... I have not gotten that email in a long time, I used to get it every time HA had to be restarted.

So, I suspect this problem is related to authentication.

**Comment by tomaae** [comment]
No, you will no longer receive repeated authentication emails. Thats intentional.
Deleting and re-adding integration was required step for update to v1.1.0 since I added new data values in setup config flow. In case it is needed again, it will be written on the top of HACS page. But I dont think so.

Entities should stay as they were. Can you check HA log for any errors?

**Comment by LanceMcCarthy** [comment]
After re-adding it, there are no more entities:

![image](https://user-images.githubusercontent.com/3520532/81739407-4f3b8880-9469-11ea-99fc-055ba64eb896.png)

Taking a look at the logs, there are a bunhc of errors, but they only look related to VScode:

```console
20-05-12 19:20:15 ERROR (MainThread) [supervisor.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-05-12 19:20:15 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-05-12 19:20:15 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
20-05-12 19:20:15 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

**Comment by tomaae** [comment]
It has to be from "custom_components.openmediavault"
If there are no errors, try to run it in debug. I never seen an issue without error in HA log yet.

**Comment by LanceMcCarthy** [comment]
Just to have a clean start, here's what I did:
1. I deleted the integration
2. Reinstalled the addon
3. Restarted HA
4. Added a new Integration and used the admin account to authenticate:

![image](https://user-images.githubusercontent.com/3520532/81745116-32f01980-9472-11ea-9a1c-a5b45592c3a7.png)

However, there are still no entities. What else can I try? I'm not familiar with enabling debug mode for integrations

**Comment by tomaae** [comment]
Debug is easy to enable
https://github.com/tomaae/homeassistant-openmediavault#enabling-debug

**Comment by ttaidapos** [comment]
I have the same problem.  Latest release of integration on hass 109.6 and adding the integration results to no devices/entities being created.  Without removing it, downgrading the integration fixes the problem but then the devices/entities get lost every few days or reboots.

See post below on latest release of the integration and error logs here:

https://community.home-assistant.io/t/openmediavault-integration/189310/8?u=ttaidapos

**Comment by tomaae** [comment]
Do you have some kind of memory card connected to omv using card reader or such?

**Comment by ttaidapos** [comment]
> Do you have some kind of memory card connected to omv using card reader or such?

Yes I do.  I have OMV 5 running on RPi4 4GB which runs on a 32GB class 10 SD Card.  Storage is connected via USB 3.0.   The odd thing is I lose both devices the storage and OMV that runs on the SD Card.

**Comment by tomaae** [comment]
That will be same as #10. I will get that fixed soon.

**Comment by ttaidapos** [comment]
> That will be same as #10. I will get that fixed soon.

Awesome, thank you!

**Comment by LanceMcCarthy** [comment]
Similar setup. Running OMV on Raspberry Pi4. Storage is 32 TB HDD (8TB x4) connected via USB 3.0 hub.

I'll try the debug log output first thing in the morning.

**Comment by tomaae** [comment]
ah okey, you dont have to do any debugs then. it will be same issue for sure.
I'm bit pressed on time with work, but I should have this solved soon.
Other then this fix, I need to implement a way to properly catch errors passed from OMV. We cant have hidden errors like these.

**Comment by ttaidapos** [comment]
By any means, no rush! Workaround is to install older version :)

**Comment by tomaae** [comment]
I will close this one and we will continue any talk in #10
