### ISSUE TITLE
Entity name change results in multiple “Unknown” entities and makes it useless

### ISSUE THREAD

**Issue by groenmarsmannetje** [tomaae/homeassistant-openmediavault#112]
In release note of latest version this change is mentioned:“Changed filesystem entity name from mountpoint to device name”

This is totally useless for me. Now I have 5 entities with the name ”Unknown” and in the attributes I also do not see the mountpoint that was originally used as entity name. I have to derive from format and disk size which device is which. Names should be understandable by default of course. So I assume that you made some assumptions for this change without validating them.

Can you please explain what the reason for this change was? And why you think this was an improvement?

**Comment by tomaae** [comment]
Mount point in internal OMV mountpoint just containind uuid, which is not recognizable or useful. Not sure what kind of setup you have to get devicename as "Unknown".
I will need to see debug to know whats wrong there.
