### ISSUE TITLE
[Bug] Fehler beim Einrichten

### ISSUE THREAD

**Issue by soeren2k** [tomaae/homeassistant-openmediavault#113]
## Describe the issue

After updating vom 1.3 to 1.4.1 settingup the integration fails. I deleted the old version, installed new version and configured it by entering user, password, ip. Also no ssl is used.

The integration seemscto start self setup but fails at any point. Error message is: error at setup

## How to reproduce the issue

1. Add integration
2. insert IP, Username, Password and select "No SSL"
3. Integration starts to initialize and show then "Fehler beim Einrichten"

## Screenshots

![image](https://user-images.githubusercontent.com/10484595/235293309-eb692b84-73e6-4e59-a58b-993801b6e098.png)

## Software versions

 - Home Assistant version:  HA 2023.4.6
 - openmediavault integration version: 1.4.1
 - openmediavault software version: 6.3.10-2 (Shaitan)

**Comment by cdjockey** [comment]
Hi I have the same problem. I have same version of HA and Openmediavault  from HACS. When I look at OMV log I get this:

> 2023-04-29 17:01:28.675 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

> 2023-04-29 17:01:28.683 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration openmediavault which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

> 2023-04-29 17:01:28.696 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration asusrouter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

> 2023-04-29 17:02:11.264 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform transmission is taking over 10 seconds.

> 2023-04-29 17:04:06.920 WARNING (SyncWorker_2) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.1.20 unable to fetch data (500)

> 2023-04-29 17:04:06.946 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OMV_New for openmediavault

> Traceback (most recent call last):
  > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)

  > File "/config/custom_components/openmediavault/__init__.py", line 35, in async_setup_entry
    await controller.async_update()

  > File "/config/custom_components/openmediavault/omv_controller.py", line 203, in async_update
    await self.hass.async_add_executor_job(self.get_compose)

  > File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)

  > File "/config/custom_components/openmediavault/omv_controller.py", line 559, in get_compose
    if "data" not in tmp:

> TypeError: argument of type 'NoneType' is not iterable

Maybe some of the above will help with fault finding?

Thanks to the developer for working on this OMV plugin/integration

**Comment by tomaae** [comment]
I'm not able to provide support in german. If you are not able to use english, we can try to wait for someone who can help you.
But you will still need to provide data from HA log.

**Comment by tomaae** [comment]
@cdjockey 
This does not have to be same issue at all. Open new issue for this one and provide debug logs. Just by line numbers it is really strange.

**Comment by soeren2k** [comment]
> I'm not able to provide support in german. If you are not able to use english, we can try to wait for someone who can help you. But you will still need to provide data from HA log.

Thanks a lot. I translated my message and I suggest the log of @cdjockey shows also my problem.

Any chance to support you?

**Comment by tomaae** [comment]
Paste your error too, it does not have to be exactly the same.

**Comment by cdjockey** [comment]
> * Home Assistant version:  HA 2023.4.6
> * openmediavault integration version: 1.4.1
> * openmediavault software version: 6.3.10-2 (Shaitan)

Hi, I have just created new issue and uploaded a log here: [https://github.com/tomaae/homeassistant-openmediavault/issues/114](url)

Thanks

**Comment by soeren2k** [comment]
Ok, Problem solved for me. Uninstalling the omv-compose extension solved the problems. Thanks for developing this cool integration!

**Comment by tomaae** [comment]
you dont need compose?

**Comment by soeren2k** [comment]
I use omv-extras with portainer. There are my docker stacks configured.

Tomaae ***@***.***> schrieb am So., 30. Apr. 2023, 01:04:
