### ISSUE TITLE
[Bug] 'Failed to set up' caused by compose plugin

### ISSUE THREAD

**Issue by cdjockey** [tomaae/homeassistant-openmediavault#114]
## Describe the issue

Integration warns 'failed to setup':

![image](https://user-images.githubusercontent.com/36975513/235302892-f52cbc9b-a7cf-45a5-9c49-f7311fd6227d.png)

## How to reproduce the issue

Updated to latest (1.4.1) version

## Expected behavior

No error after update.

## Software versions
Home Assistant version: HA 2023.4.6
openmediavault integration version: 1.4.1
openmediavault software version: 6.3.10-2 (Shaitan)

## Traceback/Error logs
Log file attached.
[home-assistant_2023-04-29T12-33-51.141Z.log](https://github.com/tomaae/homeassistant-openmediavault/files/11359190/home-assistant_2023-04-29T12-33-51.141Z.log)

**Comment by tomaae** [comment]
ok, so you are failing on compose plugin. I see you have it installed, but API returns error 500. 
can you give me screenshots from OMV UI for every compose page? are they loaging correctly?

**Comment by SamJongenelen** [comment]
I have the same i guess, NoneType is not iterable. I dont use the compose, i use portainer so maybe i need to setup OMV correctly indeed

**Comment by tomaae** [comment]
OMV still should not respond with code 500, that means internal error. Need to figure out why and if its fixable. Best would be if I could reproduce the issue.
I guess you cant see containers in OMV UI if you use portainer?

**Comment by SamJongenelen** [comment]
Well, when i navigated in omv i got error 500 too i guess its the same cause. Instruction pretty clear, but on mobile so will need to update later.
![Screenshot_20230430-100834](https://user-images.githubusercontent.com/3382443/235342793-92bfc5c0-e1fe-49e7-8c2b-b1e80d97ec52.png)

**Comment by SamJongenelen** [comment]
Ok to confirm, as soon as i gave OMV compose a file share to work from, it stopped giving 500 in the OMV UI and the integration started working again.

Didnt give it an existing path btw, just something

**Comment by cdjockey** [comment]
> Ok to confirm, as soon as i gave OMV compose a file share to work from, it stopped giving 500 in the OMV UI and the integration started working again.
> 
> Didnt give it an existing path btw, just something

I also just did this and it also seems to have solved the issue, thanks!

Maybe OMV changed something during the last update?

**Comment by SamJongenelen** [comment]
No this integration got a lot of new functions :) . The OMV api was always (6 months or so?) erroring just never consumed by this integration before

**Comment by tomaae** [comment]
I see, so it fails if shared folder is not set in compose settings? If so, we need check for that too.

**Comment by SamJongenelen** [comment]
Yeah maybe you can catch that and load the other parts of the integration, right?

**Comment by tomaae** [comment]
more like stop plugin from loading in integration and show warning. since compose query fails in that case.
