### ISSUE TITLE
1.4.1 crashes at setup parsing hwinfo

### ISSUE THREAD

**Issue by jokke-ilujo** [tomaae/homeassistant-openmediavault#116]
The hwinfo default values are not parseable.

Integration worked well prior 1.4
- Deleted the device while on old version.
- upgraded to 1.4.1
- tried to add the integration back in
- following error on entry setup

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/openmediavault/omv_controller.py:244
Integration: OpenMediaVault (documentation, issues)
First occurred: 10:29:21 (1 occurrences)
Last logged: 10:29:21

Error setting up entry OMV for openmediavault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openmediavault/__init__.py", line 34, in async_setup_entry
    await controller.async_hwinfo_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 150, in async_hwinfo_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 244, in get_hwinfo
    if int(self.data["hwinfo"]["version"].split(".")[0]) > 5:
ValueError: invalid literal for int() with base 10: 'unknown'

**Comment by tomaae** [comment]
I will need to see debugs here, but it looks like your nas is not replying correctly.
what is your omv version?

**Comment by jokke-ilujo** [comment]
6.3.10-2 (Shaitan)

I have a feeling that NginX reverse proxy was interfering. it's been misbehaving today for some reason and trying once more now to reconfigure the integration it succeeded. Not sure what was going on, but I might not be able to reproduce this.

**Comment by tomaae** [comment]
if you are using reverse proxy, it may get messy in you dont have bullet-proof implementation.
but you can always use direct access using IP for integration.
