### ISSUE TITLE
[Feature] 0.110 logos

### ISSUE THREAD

**Issue by sagitt** [tomaae/homeassistant-openmediavault#12]
new 0.110 support logos in integration for custom_components
Beta for now.

**Comment by tomaae** [comment]
I already did, they are available even in 0.109.6 now
https://github.com/home-assistant/brands/pull/1603

Icon shows up normally now.
![image](https://user-images.githubusercontent.com/23486452/82124745-487e7f80-97a1-11ea-9580-2579cf4d9269.png)
Logo does not, no idea why.

**Comment by tomaae** [comment]
Check #10 and #11 in case its the same thing

**Comment by tomaae** [comment]
even logo showed up today, I guess it just takes some time 
![image](https://user-images.githubusercontent.com/23486452/82162007-924e8f00-98a1-11ea-8c94-5ea6d51dfca9.png)
