### ISSUE TITLE
add battery level and charger status sensor

### ISSUE THREAD

**Issue by Pro-Control** [tomaae/homeassistant-openmediavault#120]
## Is your feature request related to a problem? Please describe.

I have a laptop running OMV Its always on AC power So I need every 15 days to switch the power adapter off  to let the battery level be at 20 % and turn it on again to  save battery  lifespan

## Describe the solution you'd like

I do circuit control relay to do this through ESPhome By HA  so if passable add a sensor to read  battery level and charger status it is nice  to create HA automation to do this,,

The most important sensor is 

capacity
status

all data you need it can be found in  
/sys/class/power_supply/BAT1

**Comment by Pro-Control** [comment]
I don't know why it's not posted correctly
this my post ,,

I have a laptop running OMV Its always on AC power So I need every 15 days to switch the power adapter off to let the battery level be at 20 % and turn it on again to save battery lifespan

I do circuit control relay to do this through ESPhome By HA so if passable add a sensor to read battery level and charger status it is nice to create HA automation to do this,,

Most important sensor is

capacity
status

all data you need it can be found in
/sys/class/power_supply/BAT1

**Comment by tomaae** [comment]
This is API cased integration, so anything outside of API is not possible.
