### ISSUE TITLE
[Bug] Error loading integration

### ISSUE THREAD

**Issue by mig77angel** [tomaae/homeassistant-openmediavault#121]
## Describe the issue
Error loading integration in homeassistant.

## Software versions

 - Home Assistant version: Home Assistant 2023.5.3
 - openmediavault integration version: v1.4.1
 - openmediavault software version: 6.3.12-1

## Diagnostics data

```
Logger: homeassistant.config_entries
Source: custom_components/openmediavault/omv_controller.py:559
Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues))
First occurred: 12:20:30 (1 occurrences)
Last logged: 12:20:30

Error setting up entry OMV for openmediavault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openmediavault/__init__.py", line 35, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 203, in async_update
    await self.hass.async_add_executor_job(self.get_compose)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 559, in get_compose
    if "data" not in tmp:
TypeError: argument of type 'NoneType' is not iterable
```

```
Logger: custom_components.openmediavault.omv_api
Source: custom_components/openmediavault/omv_api.py:302
Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues))
First occurred: 12:20:30 (1 occurrences)
Last logged: 12:20:30

OpenMediaVault mydomain.edited unable to fetch data (500)
```
## Additional context
It has been happening for a couple of versions, I can access omv perfectly through ssl and none of the options work when connecting, before it went well without changing anything.

**Comment by tomaae** [comment]
From what I know, it is most likely because you installed compose plugin in OMV and never configured it.
It is using wrong error message type in that case.

**Comment by mig77angel** [comment]
> From what I know, it is most likely because you installed compose plugin in OMV and never configured it. It is using wrong error message type in that case.

Hello, this plugin has already been running for a long time on my homeassistant.

**Comment by tomaae** [comment]
not sure what you mean by that

**Comment by mig77angel** [comment]
> not sure what you mean by that

It has stopped working by itself, before it did work, maybe some omv update has been the problem.

**Comment by tomaae** [comment]
I'm talking about OMV plugin "compose" that is causing issues for you.

**Comment by mig77angel** [comment]
> I'm talking about OMV plugin "compose" that is causing issues for you. You have to configure it if you plan to use it, or just uninstall it if you dont, to make integration work properly.

Thanks, that has solved the problem, but I don't understand what that affects, but that's how it's solved, thanks.
