### ISSUE TITLE
[Question] Shutdown Service not working? Maybe im doing it wrong....

### ISSUE THREAD

**Issue by remlei** [tomaae/homeassistant-openmediavault#127]
I just want my NAS to shutdown when  something is triggered.

When I test the action, it just throw a "Unknown Error"  pop-up and nothing happen.

maybe im doing it wrong? 

I used a targer using device and choose the "system", but it just throw a "Unknown Error" message, chooising the other 3 makes no sense (disk, services, filesystem) but I tried choose those instead and same error. Using the entities as target and nothing on the list makes no sense to use to shutdown my NAS.

running version 6.5.3-1 (Shaitan).

**Comment by tomaae** [comment]
you have to target uptime sensor entity.
