### ISSUE TITLE
Integration unable to fetch data

### ISSUE THREAD

**Issue by toketin** [tomaae/homeassistant-openmediavault#128]
Hi, yesterday the OMV integration on my HA suddenly has stopped working, without touching-modifying  anything on system iself. The dashboard of OMV I've seen that's working fine, while this integration is unavailable.

I've checked the logs and I've found just this error:
```

Logger: custom_components.openmediavault.omv_api
Source: custom_components/openmediavault/omv_api.py:302
Integration: OpenMediaVault (documentation, issues)
First occurred: 3 agosto 2023 alle ore 18:33:47 (1 occurrences)
Last logged: 3 agosto 2023 alle ore 18:33:47

OpenMediaVault localhost unable to fetch data (504)
```

What should I do?

Thanks!
Marco

**Comment by tomaae** [comment]
504 is gateray timeout. you nas is not responding.

**Comment by toketin** [comment]
I guessed this, but I can login into OMV webpage without problems, so it's working fine.

**Comment by tomaae** [comment]
you can try to access api and see. but it could also be network between HA and NAS.
