### ISSUE TITLE
[Bug] no sensor

### ISSUE THREAD

**Issue by sagitt** [tomaae/homeassistant-openmediavault#13]
hi, after a snapshot restore (supervisored to hassos), i can't see any sensor for OMV.... i removed integration, deleted cookie, restarted, re-create integration... all works, but i can't see any sensor.
why?

removed verify ssl certificate, i'm using it in http mode.

**Comment by tomaae** [comment]
Check #10 and #11 in case its the same thing

**Comment by sagitt** [comment]
well, ao you will fix it soon right?

**Comment by tomaae** [comment]
as soon as I find some time for it, yeah.
it has been a bit hectic lately, so I'm resting this weekend.

**Comment by sagitt** [comment]
if useful.....

![Schermata 2020-05-17 alle 21 53 04](https://user-images.githubusercontent.com/169086/82158532-d6816580-9888-11ea-8571-5aa3eb69c5db.png)

**Comment by tomaae** [comment]
yes, looks to be the same issue.
I assume you also have a memory card in your nas. Probably raspberry pi

**Comment by sagitt** [comment]
> yes, looks to be the same issue.
> I assume you also have a memory card in your nas. Probably raspberry pi

Yes rpi4

**Comment by tomaae** [comment]
Right, its a duplicate to #10 then
