### ISSUE TITLE
CPU stuck at 0% on 1.4.2 update version

### ISSUE THREAD

**Issue by RamiRihawi** [tomaae/homeassistant-openmediavault#135]
## Describe the issue

After updating to 1.4.2 everything is working again except the CPU usage, shows only 0%

## Expected behavior

The CPU load percentage should change continuously 

## Screenshots

![Vault](https://github.com/tomaae/homeassistant-openmediavault/assets/18113211/29fb6225-755d-4650-aa91-7906baa59f2c)

## Software versions

 - Home Assistant version: < HA 2023.9.2>
 - openmediavault integration version: < v1.4.2 >
 - openmediavault software version: < 6.9.0-1 (Shaitan) >

## Additional context

The system is installed on 8GB Raspberry pi 4

**Comment by tomaae** [comment]
No related to v1.4.2
duplicate to #133
