### ISSUE TITLE
[Bug] Error 500 on SMART attributes

### ISSUE THREAD

**Issue by tibouh** [tomaae/homeassistant-openmediavault#139]
## Describe the issue

I recently upgraded HA container and OMV to latest version. OMV is the OS and docker is running on top.
The existing OMV integration v1.4.2 was working fine until then. I was on HA 2023.10.x and OMV 6.9.5-2.
The OMV integration now reports an error 500 and does not update the entities.

## Software versions

 - Home Assistant version: HA 2023.11.0 in docker
 - openmediavault integration version: v1.4.2
 - openmediavault software version: 6.9.6-2

## Traceback/Error logs

From log file:
2023-11-03 09:32:39.448 DEBUG (SyncWorker_12) [custom_components.openmediavault.omv_api] OpenMediaVault <IP>:<PORT> query: Smart, getAttributes, {'devicefile': '/dev/sdd'}, {'updatelastaccess': True}
2023-11-03 09:32:39.585 WARNING (SyncWorker_12) [custom_components.openmediavault.omv_api] OpenMediaVault <IP>:<PORT> unable to fetch data (500)

From HA journal:
Logger: custom_components.openmediavault.omv_api
Source: custom_components/openmediavault/omv_api.py:302
Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues))
First occurred: 09:27:34 (17 occurrences)
Last logged: 09:43:39

**Comment by thanomichalis** [comment]
Same here as well

**Comment by tomaae** [comment]
Can you check if /dev/sdd exists?

**Comment by SeanChengN** [comment]
Maybe they modified SMART code.
https://github.com/openmediavault/openmediavault/commit/de9fb52dd6fce74e9aa8755398ec5711dcd9c3e8
![image](https://github.com/tomaae/homeassistant-openmediavault/assets/20624068/bd882996-d865-46a3-b118-83ceb61a27ee)

**Comment by SeanChengN** [comment]
This problem also occurs in version 6.9.6-1, all entities are invalid.

**Comment by tomaae** [comment]
I dont think so, its just osme cleanup and change for USB devices. Unless you actually use USB to attach storage.
Can you verify that smart works in OMV UI? such as disk temperature and smart details?

**Comment by SeanChengN** [comment]
@tomaae looks fine
![chrome_0dbSR55SZi](https://github.com/tomaae/homeassistant-openmediavault/assets/20624068/bad1a4e5-f84c-4eed-8192-757601ea4584)
![chrome_ZYxwtPOUWP](https://github.com/tomaae/homeassistant-openmediavault/assets/20624068/b7a66ce9-248a-4396-a198-32e4cba4e56b)

**Comment by tomaae** [comment]
I had a look at RPC code in OMV, but there is no change in it.
I dont have OMV on hardware so its difficult for me to figure out.
@BebeMischa could you maybe check you have same issue? to comfirm if its global problem or just something related to particular setup or ciscumstances please?

**Comment by tibouh** [comment]
My /dev/sdd is a SD card mounted on the motherboard (HP microserver gen 8) so no SMART data on that.
The SMART table goes from sdc to sde (sda to sdc being NAS drives and sde being a SSD).

**Comment by tomaae** [comment]
ah right, that was someone elses debug earlier that confused situation. Can you run integration in debug so I can see details?

**Comment by tibouh** [comment]
My /dev/sdd has "usb" on its devicefile (/dev/sde for @SeanChengN).
Here is the enumerateDevices, enumerateFilesystems and getList output:
[log.txt](https://github.com/tomaae/homeassistant-openmediavault/files/13277346/log.txt)
We can see that the integration fails when calling getAttributes on the "usb" device (same as @SeanChengN).

**Comment by tomaae** [comment]
yes, I just mixed it.
being usb device does not mean you cannot get smart info, so thats a no-go. only indicator I could find was missing wwn.
give master a try and let me know.

**Comment by conorlap** [comment]
@tomaae  - can confirm the latest master version has fixed it for me! 🥳 Thank you as always for the great support :)

**Comment by SeanChengN** [comment]
@tomaae works! Thank you!😘

**Comment by tomaae** [comment]
excellent :)

**Comment by thanomichalis** [comment]
> excellent :) just make sure you have frequent backup, flash drives as boot drive are very prone to break.

For sure. However, there is one USB Stick out there that is a SSD USB STICK. ;) 
Any idea on when it will be bumped this change to a new version?
