### ISSUE TITLE
Sensors of cpu and memory

### ISSUE THREAD

**Issue by SAOPP** [tomaae/homeassistant-openmediavault#14]
Hi!

Thanks for a integration, it's a long awaited and cool! :)

One question 'bout cpu and memory sensors, I just added the integration, and seems my cpu and memory sensors is still at zero point - it's normal or what the period for update they?

![image](https://user-images.githubusercontent.com/5647009/82451120-3c066980-9ab6-11ea-909c-eabd3773183b.png)
This screenshot for 15 minutes after integration is done.

Thanks.

**Comment by SAOPP** [comment]
Oh sorry. As I understood it's only for OpenMediaVault 5? 'coz I'm using 4.1.35-1 now.

**Comment by tomaae** [comment]
ah yes, OMV4 will be EOL at the end of next month, so adding support for it would not make sense.
I recommend upgrading, its really simple :)

**Comment by SAOPP** [comment]
Sure I thinking 'bout upgrade. Okay buddy, thanks I think I will be upgrade soon.

**Comment by tomaae** [comment]
I used [these steps](https://forum.openmediavault.org/index.php?thread/29547-solved-upgrade-from-omv-4-to-omv5/) and it was smooth transition. Even all settings stayed the same.
Of course, I set up DNS properly, not like that guide.

**Comment by tomaae** [comment]
okey, good luck :)
