### ISSUE TITLE
[Feature] Enable configuration of port of the webgui

### ISSUE THREAD

**Issue by vKnmnn** [tomaae/homeassistant-openmediavault#140]
Some people do not use openmediavault in the default configuration with the GUI on the default ports. I am one of those, so i cannot use this extension. The connection will just reach my reverse proxy on ports 80 and 443, not the omv GUI.

I'd like to suggest an additional field in the configuration of this service to accomodate for this or modify the code to use the part after ':' in the host-field as port.

**Comment by tomaae** [comment]
":" in host field works. people are using it normally.
