### ISSUE TITLE
[Bug] - CPU load and System wlanRX and TX doesn't have data

### ISSUE THREAD

**Issue by 1mfaasj** [tomaae/homeassistant-openmediavault#141]
Hi,
First of all, thanks for creating the HA integration!
I only notice a few things when I look at the sensors that are being created.
Is there perhaps an explanation for this?

OMV System CPU load remains at 0, so does not return any values.
Same for OMV System wlan0 RX and TX

Thanks
--
I'm using the latest versions of HA and your integation.

**Comment by nagydavid** [comment]
same here:

its says disable by device

<img width="574" alt="Screenshot 2023-11-30 at 19 24 01" src="https://github.com/tomaae/homeassistant-openmediavault/assets/10994218/d4954694-a381-4bd1-894b-bdadaf288516">

**Comment by 1mfaasj** [comment]
the sensor is enabled here but not showing data:
![image](https://github.com/tomaae/homeassistant-openmediavault/assets/71582854/807f11d6-81c4-43ef-811a-91696102a73a)

**Comment by tomaae** [comment]
please fill rest of information from issue template. I need to know more about your system and see diagnostics.

**Comment by nagydavid** [comment]
I have attached the diagnostics.
[config_entry-openmediavault-def75436718b976c78d64e224b3bcdcd.json.txt](https://github.com/tomaae/homeassistant-openmediavault/files/13604168/config_entry-openmediavault-def75436718b976c78d64e224b3bcdcd.json.txt)

**Comment by tomaae** [comment]
cpu issue is most likely duplicate to #133
not sure tho, as I dont know your versions.
