### ISSUE TITLE
[Bug] Cannot add OMV integration. Error!

### ISSUE THREAD

**Issue by lancercncs1** [tomaae/homeassistant-openmediavault#144]
## Describe the issue

The OMV integration had worked well for a couple of months until one day my entities stopped working. When I removed the integration and tried to re-install it, I cannot. I get a non-descriptive error "Unknown error occurred."  See screenshot below.

## How to reproduce the issue

1. Go to Settings ---> Integrations --.> Add Integration 
2. Try installing OMV

## Expected behavior

The integration should install, as it has before.

## Screenshots

![image](https://github.com/tomaae/homeassistant-openmediavault/assets/94853152/3e9fe17b-70c9-471c-9ca2-2ad3fd47827a)
## Software versions

I am on HA 2023 12.3 and using the most recent OMV 6.9.10

## Diagnostics data

I cannot even get the integration to install

## Traceback/Error logs

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: December 16, 2023 at 9:54:06 PM (10 occurrences)
Last logged: 8:08:50 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmediavault/config_flow.py", line 89, in async_step_user
    if not await self.hass.async_add_executor_job(api.connect):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmediavault/omv_api.py", line 130, in connect
    if cookies := load_cookies(self._cookie_jar_file):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmediavault/omv_api.py", line 25, in load_cookies
    return pickle_load(f)

## Additional context

I am very confused by this because this started happening out of the blue one day. Does anybody know what the issue may be? I appreciate any help I can get on this matter. Thank you!

**Comment by tomaae** [comment]
look into HA log, there should be an error

**Comment by lancercncs1** [comment]
Oh! There ARE logs. I just updated my original post above with them..

**Comment by tomaae** [comment]
yea, thats cookie of death. related to OMV API design choices.
delete file .omv_cookies.json in /config and readd your NAS to HA

**Comment by lancercncs1** [comment]
I deleted the .omv_cookies.json in /config and was able to install the integration.. However, the integration is not completely working yet. The error is now that it is "unable to fetch data." My entities are now "unavailable." Any idea of what may be causing this? Thanks!

Logger: custom_components.openmediavault.omv_api
Source: custom_components/openmediavault/omv_api.py:302
Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues))
First occurred: 12:45:31 PM (28 occurrences)
Last logged: 12:58:02 PM

OpenMediaVault 192.168.1.70 unable to fetch data (500)



![image](https://github.com/tomaae/homeassistant-openmediavault/assets/94853152/e4862a97-c89f-47c5-ae51-8bf98051d081)

**Comment by lancercncs1** [comment]
> Thanks Tomaae! I deleted the .omv_cookies.json in /config and was able to install the integration.. Unfortunately, the integration is not completely working yet. It is unable to fetch the entity data and my entities are now "unavailable." Any idea of what may be causing this?
> 
> Logger: custom_components.openmediavault.omv_api Source: custom_components/openmediavault/omv_api.py:302 Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues)) First occurred: 12:45:31 PM (28 occurrences) Last logged: 12:58:02 PM
> 
> OpenMediaVault 192.168.1.70 unable to fetch data (500)
> 
> ![image](https://private-user-images.githubusercontent.com/94853152/291094380-e4862a97-c89f-47c5-ae51-8bf98051d081.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDA4MTUsIm5iZiI6MTcwMjg0MDUxNSwicGF0aCI6Ii85NDg1MzE1Mi8yOTEwOTQzODAtZTQ4NjJhOTctYzg5Zi00N2M1LWFlNTEtOGJmOTgwNTFkMDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE5MTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZjIzZmRiOGYxMzkxZDcxMmM3N2VlNjE2NThkOWNiNjEzNWIzMjMyY2IyNjc3OWI3NDI5NzNhZjk3OGY0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tlzCeqLimyf3mldAVANHqUembE4aLxejP1pYWvFOM4)

I just

**Comment by tomaae** [comment]
thats because OMV keeps changing API all the time. try installing master version using HACS. it will most likely get fixed.
