### ISSUE TITLE
[Bug] Integration fails with error "OpenMediaVault <my_omv_ip> unable to fetch data (500)"; my OMV compose is installed and functional but not in use

### ISSUE THREAD

**Issue by mastakebob** [tomaae/homeassistant-openmediavault#152]
## Describe the issue

My HA OMV integration (v.1.4.2, installed from HACS), is giving me the repeating error "OpenMediaVault <my_omv_ip> unable to fetch data (500)".  Looking through the issue history, appears this is related to a change OMV made to its omv-extras plugin a year ago, specifically the 'openmediavault-compose' plugin.  I don't use any docker containers or compose on my OMV instance, but I did confirm that my OMV docker setup is working (created, ran, confirmed, deleted a "Portainer" container to confirm).  My OMV has no files, services, containers, images running or created.  I tried creating and running a Portainer container to see if that solved the integration issue, but no joy.  

All troubleshooting threads on this subject from 2023 all talk about 'fixing your omv' compose setup and this issue will go away.  I believe I've done that but this issue remains.  None of my OMV stats/info are being captured by Home Assistant.  

## How to reproduce the issue

1. Use this HA OMV integration with OMV 6(.9.15).  
2. Don't use any containers/compose in your OMV instance
3. 

## Expected behavior
HA OMV integration pulling my OMV status/info.  

## Software versions

All fields in this sections are required.

 - Home Assistant version: HA 2024.5.3
 - openmediavault integration version:  v1.4.2 
 - openmediavault software version:  6.9.15-2 (Shaitan)

**Comment by tomaae** [comment]
yes, if you have compose plugin installed but it is not configured, api will return error.

**Comment by mastakebob** [comment]
Thanks for the response.  I confirmed that my OMV compose plugin is installed and working (spun up a Radarr container and the webui shows).  

I"m still getting the 'unable to fetch data (500)' every minute in my logs.  Another symptom I'm seeing is that the OMV entities in HA will populate with data for about 4 seconds and then go to 'unavailable'.  This repeats every minute.  Going to the 'download diagnostics' of the OMV Integration and all of the expected data is in the json file.  But something seems to be triggering every minute that causes (1) a poll of the OMV instance which properly populates the entities, and (2) 4-5 seconds later something happens to make everything go 'unavailable'.  

Weird situation, I've not seen this in HA before...

**Comment by tomaae** [comment]
that means error occurs mid pull. run it in debug and we will see when it fails.

**Comment by mastakebob** [comment]
[home-assistant_openmediavault_2024-05-16T12-01-22.776Z.log](https://github.com/tomaae/homeassistant-openmediavault/files/15334763/home-assistant_openmediavault_2024-05-16T12-01-22.776Z.log)

Thanks!  debug log attached (I removed all of the stuff before I enabled 'debug mode' on the OMV integration. I took a skim through but its too much for me to parse without an idea of where to start..

**Comment by mastakebob** [comment]
Hmm, I selected 'disable SMART' in the integration configuration option and it immediately started working as expected.  Also returned 2 new devices ("Services" and "Compose").  So seems likely that either my OMV's SMART setup is incorrect and throwing off 'bad' data, or the HA OMV Integration has trouble parsing the SMART data?

I don't really need SMART data so I'll likely just leave it with SMART disabled.
