### ISSUE TITLE
[Question] Can I get back ethernet informations on PI4?

### ISSUE THREAD

**Issue by dunkelheim** [tomaae/homeassistant-openmediavault#157]
Hi,

I just switched my OMV from a PI 3 to a PI4. After connceting my system to HA everything went fine except the up- and download over ethernet. WLAN is shown as sensor but disabled in my System.
Is it possible to get the sensors from the pi4 too?

new:
![image](https://github.com/user-attachments/assets/1fa9201d-0594-4f2e-88e6-59bb28bcd4b3)

old:
![image](https://github.com/user-attachments/assets/883badb9-852b-4a3a-a8d8-426d5bdf8f60)

Thanks

**Comment by Andy1910** [comment]
same problem but i have noticed that eth0 has been renamed to end0 in bookworm if i run ifconfig

**Comment by dunkelheim** [comment]
After trying to fix the code in the integration, i finally found an easy solution: changing things on the OMV side.
To do this I opend my pi via ssh, typed the following into the comand line:
`sudo nano /boot/firmware/cmdline.txt`
adding `net.ifnames=0` at the end, save and reboot. After rebooting HA as well, up- and download are back again.
Hope this will help you, if you've got the same issue.

**Comment by logicbus** [comment]
This did not work for me.  

In fact, when I made this change, HA didn't display any data from OMV.  

I had to create cmdline.txt (and the firmware folder) to try this fix, so after it didn't work, I deleted it and the firmware folder.  I rebooted OMV, reloaded the configuration, and I'm back to where I was.  Still no ethernet info.

**Comment by Andy1910** [comment]
i think the correct cmd is sudo nano /boot/cmdline.txt  
after rootwait leave a space and add net.ifnames=0

**Comment by logicbus** [comment]
Sure enough, /boot/cmdline.txt existed already.  I made the addition there, rebooted the Pi, and reloaded the OMV configuration in HA.  Once again I see OMV network traffic in HA.  

Thanks!

**Comment by dunkelheim** [comment]
short response after i had to rebuild my system. When I opened @Andy1910s file, I got this one.
![image](https://github.com/user-attachments/assets/8ae0ca95-9bd4-4c43-bb79-1d6245dd5c79)

So may try both, if the first one doesn't work for you. The solution is the the same in both files.
