### ISSUE TITLE
[Feature] Add Uptime Sensor 

### ISSUE THREAD

**Issue by kdvlr** [tomaae/homeassistant-openmediavault#16]
Would it be possible to add an uptime sensor to this component ?

**Comment by tomaae** [comment]
Not sure, what would be a purpose for an uptime sensor?

**Comment by kdvlr** [comment]
I use HomeAssistant as a monitoring dashboard for my servers and sometimes, due to various reasons, my machines crash (and recover). I use uptime to monitor if some servers had randomly restarted. 

Also, most monitoring software (including OMV) display uptime as part of their summary.

**Comment by tomaae** [comment]
Got it, it makes sense. I will look into it.

**Comment by tomaae** [comment]
Uptime sensor is available in v1.1.3

**Comment by PascalBu** [comment]
> Uptime sensor is available in v1.1.3

Nice work, however I think it needs a recalculation?

![Screenshot_20200603-124109](https://user-images.githubusercontent.com/47149320/83627692-9fed5f80-a597-11ea-94cc-13ff2f1ecb70.jpg)

**Comment by tomaae** [comment]
woops

**Comment by tomaae** [comment]
fixed in v1.1.4

**Comment by kdvlr** [comment]
Awesome !!! Thank you so much

**Comment by tomaae** [comment]
no problem, feel free to suggest features.
I have implemented everything that would be useful for me (except services for now, since they are tricky). But I'm sure there are lot more things I'm missing.
