### ISSUE TITLE
I can't see OpenMediaVault in integrations 

### ISSUE THREAD

**Issue by simulot** [tomaae/homeassistant-openmediavault#17]
## Describe the issue
I wan't to add OWV integration to my home assistant installation. But after install it with HACS, and refresh the cash, and several restart, the integration isn't availble. 

## How to reproduce the issue
- add the integration with HACS
- go to configuration / integration / +
- Search for OpenMediaVault

## Expected behavior
OMV integration visible in the list

## Software versions

 - Home Assistant version: v0.111.3
 - openmediavault integration version: v1.1.5
 - openmediavault software version: 5.5.2-1

**Comment by rexer78** [comment]
I Have the same problem 
Home Assistant version: v0.111.4
openmediavault integration version: v1.1.5
openmediavault software version: 5.5.2-1

**Comment by tomaae** [comment]
I dont think thats related to integration. There was such issue before, but person fixed it themselves.
Best to check logs is it is loaded or if there are any errors.

**Comment by rexer78** [comment]
after a host reboot now the integration is availble. thanks

**Comment by simulot** [comment]
Indeed... I have rebooted the OMV server, which also hosts Homeassistant, and it works.
Thanks
