### ISSUE TITLE
[Feature] Power Management Support

### ISSUE THREAD

**Issue by sanyadez** [tomaae/homeassistant-openmediavault#20]
Is there any plans to implement power off, power on by sending WoL package and rebooting? This will be good feature to power off for example after enabling alarm without using ssh commands in HA, etc.

**Comment by BebeMischa** [comment]
I would love this too ;-)

**Comment by mredone** [comment]
It will be superb when this option will be added. It can be automated off nas when is no people in home and start when someone back to home.

**Comment by xiaobao1980** [comment]
希望早点实现这个功能 谢谢

**Comment by jorgezazo** [comment]
I would love to have a turn off system in this integration... it will avoid installing other servers at OMV host and a lot of work with workarounds.

**Comment by NobleWolf** [comment]
I would appreciate this enhancement as well.
In the mean time @sanyadez what are you using for shutdown and WoL for right now?
