### ISSUE TITLE
[Feature] ability to change port

### ISSUE THREAD

**Issue by gw1gw1** [tomaae/homeassistant-openmediavault#21]
Hi, 

This would be nice to be able to select the port we want when doing the setup. 

Indeed due to other applications using port 80 I had to change omv port. 

Great job anyway!

**Comment by Andre3-3** [comment]
I would also like to mention that this would be a very useful feature.

**Comment by Andre3-3** [comment]
Thanks I figured it out!

**Comment by gw1gw1** [comment]
Works perfectly. In case people are looking for the answer here is how to do it

![omv](https://user-images.githubusercontent.com/47014001/98812688-36fdf380-2423-11eb-939e-6e447de8c474.jpg)
