### ISSUE TITLE
Detected I/O inside the event loop [Bug]

### ISSUE THREAD

**Issue by haberda** [tomaae/homeassistant-openmediavault#23]
## Describe the issue

Hello, I am getting the error spelled out below in my home-assistant logs. It still works but might become an issue in the future.

## Software versions

 - Home Assistant version: 0.118.4
 - openmediavault integration version: latest
 - openmediavault software version: 5.5.17

## Traceback/Error logs

Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 6:21:30 PM (1 occurrences)
Last logged: 6:21:30 PM
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for openmediavault doing I/O at custom_components/openmediavault/omv_api.py, line 128: response = self._connection.post(

**Comment by tomaae** [comment]
This should not happen outside of integration setup. Do you know when this occurs?

**Comment by haberda** [comment]
Yeah, sorry please ignore.

For some reason this integration stopped working, so I uninstalled and re-installed it. On re-install this was in my log, so I figured it may have been related to why it lost connection. For some reason lately it keeps losing connection. If I can figure out why, I'll post another ticket.

Thanks for the great integration!
