### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by HaViGit** [tomaae/homeassistant-openmediavault#29]
Is it possible to install manual, without HACS?

**Comment by HaViGit** [comment]
Thanks for helping! After adding the extracted custom_components map to Home Assistant and a reboot I can select the OMV integration (image) but when I click the popup closes immidiately and the integration is not shown. Any suggestion? 

![Screenshot](https://user-images.githubusercontent.com/46343309/105831261-c9e01000-5fc6-11eb-90d0-8438b8936b5c.png)

**Comment by HaViGit** [comment]
After a re-install and a fresh boot it remains the same and no relevant info in the log :-(

**Comment by HaViGit** [comment]
Cache cleared, HA (0.116.4) and PC (Win10 latest) restarted, tried another browser and tested on an iPad, unfortunately without success. I'm afraid I'll have to give up but thank you for your help anyway!

**Comment by tomaae** [comment]
ah right, did you used openmediavault.zip from release? if you used source code or commit, you will be missing translation files.

**Comment by HaViGit** [comment]
Yes, I did and in the image the files in my Home Assistant installation. As you can see it includes the en.json file.

<img width="666" alt="map" src="https://user-images.githubusercontent.com/46343309/105880365-940d4c80-6003-11eb-9c76-e2036e62be26.PNG">

**Comment by tomaae** [comment]
not sure whats going on then. I assume it has correct filesystem permissions.

**Comment by HaViGit** [comment]
Thanks again for your help. I haven't changed the permissions so I can't say this is the problem. But I don't continue with OMV, my setup (ROCKPro64) show the issue that many people report on the OMV forum. The transfer speed starts at 100+ mb / sec and drops to <1 mb / sec after a few seconds. There are many complaints about this, but no real solution has been found. OMV seems not reliable and not well supported at this point, so my new NAS has been ordered ;-)

**Comment by HaViGit** [comment]
It is not acceptable to have a (backup) OMV server that you cannot trust. In that case, it is indeed better to buy something else.
