### ISSUE TITLE
Login notification email sent by OMV on every HA restart

### ISSUE THREAD

**Issue by sagitt** [tomaae/homeassistant-openmediavault#3]
good work for this integration
every time i restart home assistant i receive an email for access from my user.

there is a way for fix this without disabling email alerts for this event?

**Comment by tomaae** [comment]
No idea, most likely not.

**Comment by sagitt** [comment]
try it, enable notifications and restart hass :)

with browser, saving cookie i think, only the fist login have this alert.

**Comment by tomaae** [comment]
yes, I know it will send a notification. I'm getting it every time too.
OMV stores cookies with various quotes from books to track this. But right now, I dont know about any way to store a cookie jar within HA.

**Comment by sagitt** [comment]
> yes, I know it will send a notification. I'm getting it every time too.
> OMV stores cookies with various quotes from books to track this. But right now, I dont know about any way to store a cookie jar within HA.

Maybe a request to dev? I talked with it on github sometime for bugs. It’s active developer

**Comment by tomaae** [comment]
Solved in v1.0.1

**Comment by sagitt** [comment]
Well :)

**Comment by tomaae** [comment]
lets hope that storing those book quotes wont be considered a copyright infringement ;D

**Comment by sagitt** [comment]
😂😂
