### ISSUE TITLE
[Feature] Add support without HACS

### ISSUE THREAD

**Issue by Weltraumpenner** [tomaae/homeassistant-openmediavault#30]
I don't use HACS, but would really like to use your custom component.

It would be awesome, if you would add the possibility to add your custom_component manually, by adding it to the custom_components-folder and add an entry to the integration.yaml.

**Comment by tomaae** [comment]
there is nothing to add, it will work. all HACS does is provide convenience of having everything in one place and update notifications.

**Comment by Weltraumpenner** [comment]
Sorry, I didn't knew that! 
Could you tell me how the configuration.ini should look like?

**Comment by Weltraumpenner** [comment]
A, thanks a lot, it's working now! :-)
Maybe it would make sense to add a manual installation-section to the readme?
For me it wasn't clear that I have to set it up over the integrations-page after adding it to custom_components.
