### ISSUE TITLE
OMV integration appears in HA, can't see or find any entities. 

### ISSUE THREAD

**Issue by MisterTFM** [tomaae/homeassistant-openmediavault#32]
## Software versions

 - Home Assistant version:  2021.2.2
 - openmediavault integration version: 
 - openmediavault software version: 5.5.23-1

**Comment by MisterTFM** [comment]
Where and how does OMV need setup in HA? I can see the integration, that’s all.[Image.jpeg]

Sent from iphone.
________________________________

**Comment by MisterTFM** [comment]
[cid:cee23cf3-bb1f-404a-ad4f-587d19fc4a26]

________________________________

**Comment by tomaae** [comment]
Set it up in integrations. Like with any other integration.
If you are new to HA, you can follow this:
https://github.com/tomaae/homeassistant-openmediavault#setup-integration

**Comment by silmaril464** [comment]
I have installed from HACS. However, the integration does not appear in settings -> integrations -> add integration.
I can't add integration because it doesn't appear in the homeassistant integrations menu

**Comment by keshabit** [comment]
> This happened to someone already, but it is not related to integration itself.
> 
> Could be filesystem access rights or some other issue. Just check them and reinstall it.

I've installed integration using HACS, I can see folder in custom_components but I can't see OMV option in integration. I've added other integration never encountered such issue.

**Comment by tomaae** [comment]
delete browser cache, its common issue.
