### ISSUE TITLE
[Feature] Lan activity

### ISSUE THREAD

**Issue by Sawadee2u** [tomaae/homeassistant-openmediavault#33]
Could you add LAN data in and out? This would be very useful.
Also Disk capacity info: amount used, amount available. etc.
Thanks

**Comment by tomaae** [comment]
Network activity does not seem to be available using API.

**Comment by tomaae** [comment]
got it confirmed, web interface just uses embedded rrd graphs

**Comment by tomaae** [comment]
Reopened as it was implemented in upcoming OMV 6.0.18-1
https://github.com/openmediavault/openmediavault/issues/1247

**Comment by SamJongenelen** [comment]
So, i'm new to the language, but have found the relevant API code in the OMV repository:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/network.inc

RPC name:
>  Network
The object is return as following:
>  $obj['type'] = $iface->getType();
$obj['description'] = $iface->getDescription();
$obj['stats'] = !$stats ? [] : $stats;
$obj['gateway'] = !$gateway ? "" : $gateway;
$obj['gateway6'] = !$gateway6 ? "" : $gateway6;
$obj['address'] = !$address ? "" : $address;
$obj['address6'] = !$address6 ? "" : $address6;
$obj['prefix'] = !$prefix ? -1 : $prefix;
$obj['prefix6'] = !$prefix6 ? -1 : $prefix6;
$obj['netmask'] = !$netmask ? "" : $netmask;
$obj['netmask6'] = !$netmask6 ? -1 : $netmask6;
$obj['ether'] = !$ether ? "" : $ether;
$obj['mtu'] = $iface->getMTU();
$obj['state'] = !$state ? gettext("UNKNOWN") : $state;
$obj['link'] = $iface->getLink();
$obj['speed'] = !$speed ? -1 : $speed;
