### ISSUE TITLE
[Question] user rights

### ISSUE THREAD

**Issue by ElVit** [tomaae/homeassistant-openmediavault#34]
Hi tomaae,
First of all, thanks for this addon.
I would like create a custom user in omv which is only for this addon. This user shall have as few rights as possible. 
Can you tell me what user groups I have to set in omv to get all devices/entities/sensors in Home Assistant?
Thanks

**Comment by tomaae** [comment]
Looks like right now only "admin" username can use API. Its hardcoded in OMV.

RPC role:
```
"role" => ($username === "admin") ? OMV_ROLE_ADMINISTRATOR : OMV_ROLE_USER
```

API validation:
```
		$this->validateMethodContext($context, [
			"role" => OMV_ROLE_ADMINISTRATOR
		]);
```
