### ISSUE TITLE
[Bug] Detected I/O inside the event loop

### ISSUE THREAD

**Issue by ShonP40** [tomaae/homeassistant-openmediavault#41]
## Describe the issue
Home Assistant errors while trying to setup the integration.

## How to reproduce the issue
1. Install the integration
2. Try to add it
3. You'll see a message saying "Unknown Error" after pressing on submit

## Expected behavior
Expected the integration to complete the setup

## Software versions

 - Home Assistant version: 2021.4.2
 - openmediavault integration version: v1.1.5
 - openmediavault software version: 5.6.3-1

## Traceback/Error logs
```
WARNING  (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for openmediavault doing I/O at custom_components/openmediavault/omv_api.py, line 134: response = self._connection.post(
```
```
ERROR (MainThread) [custom_components.openmediavault.omv_api] OpenMediaVault (IP) error while connect : unknown
```

## Additional context
I tried to set it up with and without SSL. Got the same result.

I am aware that an issue similar to this was created already, but it was closed&locked without a solution.

**Comment by tomaae** [comment]
It is most likely refused connection by OMV or wrong port.
If you are using SSL without verified certificate, uncheck validate SSL.

**Comment by ShonP40** [comment]
I have OMV set to port 80 for normal connections and 443 for SSL

(I did uncheck the SSL verification box)

**Comment by tomaae** [comment]
do you get same error as in #42 ?

**Comment by ShonP40** [comment]
Yea

**Comment by tomaae** [comment]
ok, we will continue in #42
