### ISSUE TITLE
Continuous disconnections.

### ISSUE THREAD

**Issue by Gino1606** [tomaae/homeassistant-openmediavault#43]
Hi Tomaae I have opened a new ticket.
Practically there are continuous disconnections of the integration creating an error in the LOG. Also in the event log it always says entity not available.
I am attaching the LOG photos from the reboot as you asked me, hoping it will be useful.
The SSL certificate of HA for remote access works with duckdns.
I run supervised home assistant in docker version 2021.04.03 with your integration 1.1.6 and OVM 5.6.4.1 Usul.
I'm at your disposal, thank you very much in advance. You are the only one who can help me.

![Immagine 2021-04-14 212358](https://user-images.githubusercontent.com/73401150/114770114-5b138700-9d6b-11eb-98c4-2f7a7aeb4c42.jpg)
![Immagine 2021-04-14 213229](https://user-images.githubusercontent.com/73401150/114770119-5c44b400-9d6b-11eb-94ba-42f54a0a22f9.jpg)
![Immagine 2021-04-14 213407](https://user-images.githubusercontent.com/73401150/114770120-5c44b400-9d6b-11eb-83b2-5a6edcaed524.jpg)
![Immagine 2021-04-14 211055](https://user-images.githubusercontent.com/73401150/114770121-5c44b400-9d6b-11eb-9e33-be3aab579366.jpg)

**Comment by Gino1606** [comment]
I don't know if it can be useful, HA runs on the same raspberry pi4 where OMV is located.
I am attaching another log that I captured earlier.
![IMG_20210414_194817](https://user-images.githubusercontent.com/73401150/114776155-703fe400-9d72-11eb-8fbd-933504351028.jpg)

**Comment by tomaae** [comment]
I need debugs from the integration. Also, please upload the them in text file, not screenshots.

**Comment by Gino1606** [comment]
[LOG OMV.txt](https://github.com/tomaae/homeassistant-openmediavault/files/6320621/LOG.OMV.txt)
Tomaae sorry for the delay, I have attached the txt file with the OMV logs taken on the HA core. Fingers crossed...

**Comment by tomaae** [comment]
oh, I missed this somehow, sorry.
Looks like OMV times out when trying to query smart data /dev/sda
Can you try it manually in OMV?

**Comment by Gino1606** [comment]
sda is a hard-disk that works in OMV. how should i test it? sorry I did not understand.

**Comment by BebeMischa** [comment]
/dev/sda is, when standart installation, the system drive. 

try this: 
![image](https://user-images.githubusercontent.com/73079275/117194520-790d5e00-ade4-11eb-8137-b515c072a2da.png)

**Comment by tomaae** [comment]
Pretty sure Gino has system on flash disk.
That may also be the issue since those can die selectively really fast. But I'm not able to verify that kind of failure.

**Comment by BebeMischa** [comment]
then that could be also the problem, maybe? USB flashdisks are not SMART capable, as far, as i know. So maybe there is a query for SMART data on a disk, which does not have SMART functions enabled?

Gino, check that out... ;-)

**Comment by Gino1606** [comment]
I have the OMV system disk on a Raspberry 4 micro SD. The Smart function is disabled. The SDA query in my case is the system hard drive. I am attaching the photos. Do you think that's the problem? It seems as if the apu stop questioning.
![IMG_20210506_145459](https://user-images.githubusercontent.com/73401150/117303330-e10f8300-ae7c-11eb-8370-47a5217f83eb.jpg)
![IMG_20210506_145518](https://user-images.githubusercontent.com/73401150/117303335-e1a81980-ae7c-11eb-8e9a-723b1d5dbba0.jpg)
![IMG_20210506_145636](https://user-images.githubusercontent.com/73401150/117303338-e240b000-ae7c-11eb-938c-f4ba9c0e0c22.jpg)
![IMG_20210506_145657](https://user-images.githubusercontent.com/73401150/117303339-e2d94680-ae7c-11eb-8adb-485c086c37ff.jpg)

**Comment by Gino1606** [comment]
Sorry, I was wrong. The SDA disk is the storage disk, not the system disk.

**Comment by tomaae** [comment]
looks good to me. if you go into smart and click information on sda, will it work?

**Comment by Gino1606** [comment]
You are both right, the problem is on the sda ​​drive. I tried to detach it from the raspberry and your integration works perfectly.
Now I close the problem on github ;-)
Tomaae why this behavior of the disc?
Do you need any specific disks?

**Comment by Gino1606** [comment]
I changed hard-disk with one from Western Digital and now everything works. The old one, as you said, did not read on Smart menu info.
It was you  @tomaae  and @BebeMischa  really great.
Thank you...
