### ISSUE TITLE
[Bug] Error on startup in 2021.5.0b1

### ISSUE THREAD

**Issue by firstof9** [tomaae/homeassistant-openmediavault#45]
## Describe the issue

Error on startup of Home Assistant

## How to reproduce the issue

Start 2021.5.0b1 with OMV

## Expected behavior

No startup errors.

## Screenshots

n/a

## Software versions

 - Home Assistant version: 2021.5.0b1 
 - openmediavault integration version: 1.1.6
 - openmediavault software version: 5.6.5-1

## Traceback/Error logs

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/openmediavault/__init__.py", line 38, in async_setup_entry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 266, in async_get_or_create
    raise RequiredParameterMissing(["identifiers", "connections"])
homeassistant.exceptions.RequiredParameterMissing: (RequiredParameterMissing(...), 'Call must include at least one of the following parameters: identifiers, connections')
```

**Comment by firstof9** [comment]
🤷‍♂️ shows up in b3 as well.

**Comment by firstof9** [comment]
Here's the change that causes the error:
https://github.com/home-assistant/core/pull/49038

**Comment by firstof9** [comment]
Just looks like you're missing a `connections` or `identifiers` key, here's an example:

https://github.com/home-assistant/core/blob/29d72714f3786d959805ec23d259b09a00e1b936/homeassistant/components/esphome/__init__.py#L461

**Comment by tomaae** [comment]
Could you test it? I have no way to test OMV myself at the moment.

**Comment by firstof9** [comment]
That appears to resolve the issue.

**Comment by firstof9** [comment]
Just a note it does give you an additional device with no entities:

![image](https://user-images.githubusercontent.com/1105672/117031132-25502700-acb5-11eb-8858-2af62508cbdb.png)

**Comment by firstof9** [comment]
Sounds fine for a small hotfix to me. 👍

**Comment by tomaae** [comment]
Released new version with this fix.
