### ISSUE TITLE
Support for CPU temperature

### ISSUE THREAD

**Issue by sagitt** [tomaae/homeassistant-openmediavault#46]
## Is your feature request related to a problem? Please describe.
Hi, i have my OMV server in a rack with fans, i want to start fan on hight server cpu temperature
What do you think about expose it like drives temperature?

## Describe alternatives you've considered
For now i'm using MQTT to expose it but i think will be better with this integration.

**Comment by tomaae** [comment]
Does OMV API presents this information?
MQTT is different, you are getting it from OS.

**Comment by sagitt** [comment]
> Does OMV API presents this information?
> MQTT is different, you are getting it from OS.

I don’t know
