### ISSUE TITLE
In Core Log : "Adding certificate verification is strongly advised."

### ISSUE THREAD

**Issue by Dim3333** [tomaae/homeassistant-openmediavault#54]
Hello,

In log of Core, this message appears (every minutes):

`/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.x.x'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(`

192.168.x.x is the IP of my NAS. (OMV)

Thanks for your help.

**Comment by tomaae** [comment]
This integration does not use urllib3 directly.
Check verify ssl certificate if you have valid certificate. I wont be able to test this myself tho.
