### ISSUE TITLE
unable to add openmediavault integration (not listed)

### ISSUE THREAD

**Issue by FredLeudon** [tomaae/homeassistant-openmediavault#56]
## Describe the issue
Installed openmediavault using HACS.
openmediavault  is located on custom_copoment directory
ha core logs says : 2021-09-17 07:09:48 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration renault which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

when I go to configuration / integrations / add / search 'openmedia....' component dosent appears in list.

## How to reproduce the issue
dont know

## Expected behavior
view OpenMediaVault in integration list.

## Screenshots
![Capture d’écran 2021-09-17 à 08 31 53](https://user-images.githubusercontent.com/12695496/133735794-ec72c247-f8eb-4834-bf57-67807271f374.png)

## Software versions
 - Home Assistant version: supervisor-2021.09.0 / core-2021.9.6
 - openmediavault integration version: 1.1.7
 - openmediavault software version: 5.6.14-1 (Usul)

**Comment by BebeMischa** [comment]
integration name is OMV in the list. Not Openm... ;-)

**Comment by FredLeudon** [comment]
thanks, but didn't find using O..
![Capture d’écran 2021-09-17 à 09 06 42](https://user-images.githubusercontent.com/12695496/133739717-7b8dff89-5139-4ae4-a3b6-cae990871a41.png)
..

**Comment by tomaae** [comment]
That is caused by your browser cache. Happens often when you install integrations, specially with chrome.
Just clear your cache.

**Comment by FredLeudon** [comment]
It works, thanks a lot !
