### ISSUE TITLE
Problems with Login[Question]

### ISSUE THREAD

**Issue by Kimosaj** [tomaae/homeassistant-openmediavault#59]
Hi, I recently installed this Integration in my Homeassistant. But I have a problem with my login. I have a user for my own to get access to the storage, but with this user it seems that I have not enough rights to get informations about CPU load etc.
When I create a new user where I would give the specific rights there is an error message with the login.
This is the error message: [%key:common::config_flow::error::cannot_connect%]
Whats wrong. Additionaly the informationtext for the credentialtextboxes are looking like this: [%key:common::config_flow::data::ssl%]
Is something wrong with the installation of the repository?

**Comment by tomaae** [comment]
make sure you are using omv 5. integration does not work with omv 6.
otherwise its just access rights

**Comment by Kimosaj** [comment]
Thanks for answer, but I already checked if I´m using OMV 5. Is anything to look for the choice of my password? Any special character I may not use? Because the user works fine in OMV but in the integration it will not accept any of these.

**Comment by tomaae** [comment]
try build in admin. that one should have correct rights.
