### ISSUE TITLE
[Bug] Integration no longer working? 

### ISSUE THREAD

**Issue by CZonin** [tomaae/homeassistant-openmediavault#60]
## Describe the issue
My OMV entities all started showing as 'Unavailable' 2 days ago in HA. I tried to remove the integration and add it back but it gives errors when trying to enter my OMV info.

## Screenshots
This is what it looks like when trying to add the integration now:
![Screenshot 2021-12-04 082917](https://user-images.githubusercontent.com/67965669/144711315-445456f3-1422-4ec4-9b73-3e0f80b48b69.png)

## Software versions

 - Home Assistant version: core-2021.11.5
 - openmediavault software version: 5.6.21-2

**Comment by BebeMischa** [comment]
Just to inform, here it works fine, so it's not global issue ;-)

**Comment by tomaae** [comment]
no idea, check what you changed in OMV.
Those translation keys are kind of weird, they are build-in to HA.

**Comment by CZonin** [comment]
> 

I haven't made any changes other than updating my OMV. Is there something I should check on the OMV side or do you think it's an issue with my HA?

**Comment by tomaae** [comment]
well, thats quite a big thing. which version did you had and what is your new version?

**Comment by AndreaPro** [comment]
I have exactly the same issue, I am using OMV 5.6.21-2 and HomeAssistant Core 2021.11.5 from the linuxerver.io docker image

**Comment by BebeMischa** [comment]
Just to help my imagination a bit, a question:

Are your HA and OMV instances running on the same machine?

**Comment by AndreaPro** [comment]
> Just to help my imagination a bit, a question:
> 
> Are your HA and OMV instances running on the same machine?

Yes, they are

**Comment by CZonin** [comment]
I was able to get it working again by removing the main integration as well as the one in HACS, and deleting config/.omv_cookies.json and then rebooted. I then readded through HACS then the main integration. The set up screen still looked like it did in my screenshot above, but it was able to successfully add it this time.

My HA and OMV are each running on a separate Pi 4.

**Comment by tomaae** [comment]
Could have been stuck cookie, yea. They can be pain sometimes.

**Comment by AndreaPro** [comment]
> I was able to get it working again by removing the main integration as well as the one in HACS, and deleting config/.omv_cookies.json and then restarted HA. I then readded through HACS then the main integration. The set up screen still looked like it did in my screenshot above, but it was able to successfully add it this time.
> 
> My HA and OMV are each running on a separate Pi 4.

I'll try It ASAP, I have installed it yesterday for the first time and I hope that it fixes the issue for me too

**Comment by AndreaPro** [comment]
I've tried now and it worked for me too! Even in my case the setup screen shown the same issue but this time after the setup the entities are working

**Comment by mezen** [comment]
Fresh (and first time) installation of this OpenMediaVault integration and I also get those weird translation keys. Too spooky to continue integration, even I dont know what to put into these edit fields.

**Comment by tomaae** [comment]
I'm pretty sure this was not the case before, probably some change in HA.
Its nothing to worry about, its just translation stuff for config, related to https://github.com/tomaae/homeassistant-openmediavault/pull/28
I'm really busy right now with my other projects, specially with all the changes that been added to HA and I want to take advantage of. 
Hopefully someone with OMV can help with this. If not, I will eventually set up OMV somewhere, but that may take more time as I would need to get my hands on some spare PC. VM just wont do here unfortunately.

**Comment by BebeMischa** [comment]
If you want met to test something, @tomaae , just ask... ;-)

**Comment by tomaae** [comment]
Thanks for offer, but its something I need for active development, not just test :)
No idea what was changed and documentation is pretty much non-existant with OMV.
