### ISSUE TITLE
[Bug] Sensor property renamed from `device_state_attributes` to `extra_state_attributes` in HA core

### ISSUE THREAD

**Issue by firstof9** [tomaae/homeassistant-openmediavault#61]
## Describe the issue

`device_state_attributes` is deprecated and needs to be changed to `extra_state_attributes`

## How to reproduce the issue

Run HA 2021.12.0+

## Expected behavior

n/a

## Screenshots

n/a

## Software versions

 - Home Assistant version: 2021.12.0b1
 - openmediavault integration version: n/a
 - openmediavault software version: n/a

## Traceback/Error logs

```
(<class 'custom_components.openmediavault.binary_sensor.OMVBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.

(<class 'custom_components.openmediavault.sensor.OMVSensor'>) implements device_state_attributes. Please report it to the custom component author.

(<class 'custom_components.openmediavault.sensor.OMVFileSystemSensor'>) implements device_state_attributes. Please report it to the custom component author.

(<class 'custom_components.openmediavault.sensor.OMVDiskSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

## Additional context

n/a

**Comment by tomaae** [comment]
thanks :)
btw, no need to spend extra time to open issue. PR is more then enough :)

**Comment by firstof9** [comment]
I opened it as I didn't have time at the time to get to a PR hehe but 👍

**Comment by tomaae** [comment]
I dont mind, its just to save your time :-)
