### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by BartEngelen** [tomaae/homeassistant-openmediavault#64]
I get the following error in my log. It just needs 'device' changing to 'extra' in the relevant method.
![image](https://user-images.githubusercontent.com/17978789/145794438-3340c39e-9057-4258-ab84-19fe4a969126.png)

**Comment by BebeMischa** [comment]
see this closed issue:
https://github.com/tomaae/homeassistant-openmediavault/issues/63

**Comment by BartEngelen** [comment]
Thanks!
