### ISSUE TITLE
Warning on new 2021.12

### ISSUE THREAD

**Issue by sagitt** [tomaae/homeassistant-openmediavault#65]
After upgrade 2021.12 i see this warning:
There is a way to fix it?

Dettagli registro (AVVERTIMENTO)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 00:41:38 (15 occurrences)
Last logged: 00:41:45

Entity sensor.nas_sda (<class 'custom_components.openmediavault.sensor.OMVDiskSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.nas_sdb (<class 'custom_components.openmediavault.sensor.OMVDiskSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.nas_update_available (<class 'custom_components.openmediavault.binary_sensor.OMVBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.nas_reboot_pending (<class 'custom_components.openmediavault.binary_sensor.OMVBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.nas_config_dirty (<class 'custom_components.openmediavault.binary_sensor.OMVBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by tomaae** [comment]
already fixed in #61
