### ISSUE TITLE
[Feature] OMV 6 support

### ISSUE THREAD

**Issue by Hukuma1** [tomaae/homeassistant-openmediavault#67]
Currently experiencing the same issue of not being able to get past the login credentials screen as per https://github.com/tomaae/homeassistant-openmediavault/issues/60. These look like HA changes.

But also noticed you wanted someone with OMV v6 to help you test any API changes. Let me know, I'd love to add support for this as I recently upgraded to v6. It's been super stable for me, and I think it will be finally promoted to stable shortly.

Right now trying this on with the following.
HA version `core-2022.2.0b0`
OMV version `6.0.9-5`

<img width="288" alt="omv" src="https://user-images.githubusercontent.com/54511555/151421516-195e3fa4-d1bc-4601-9424-e319fe2a504c.png">

```
Logger: custom_components.openmediavault.omv_api
Source: custom_components/openmediavault/omv_api.py:105
OpenMediaVault 192.168.1.4 error while connect : unknown
```

```
Logger: custom_components.openmediavault.config_flow
Source: custom_components/openmediavault/config_flow.py:76
OpenMediaVault connect error
OpenMediaVault cannot_connect connect error
```

**Comment by tomaae** [comment]
But really, this is not something I can do without access to OMV6. Just testing is not enough.
Right now I dont have spare hardware to build whole pc for this.

**Comment by Hukuma1** [comment]
Anything I can provide from my end? Any file info from my setup?

**Comment by tomaae** [comment]
Not really. Its not just adding simple feature, but support for completely new thing.

**Comment by NdR91** [comment]
Hello, I just saw your comment here:
[](https://community.home-assistant.io/t/openmediavault-integration/189310/67?u=ndr)

OMV6 user here, if I can provide some data/info, let me know.

**Comment by BebeMischa** [comment]
Questions about API documentation are dropped here:
https://forum.openmediavault.org/index.php?thread/42487-omv-6-api/&postID=306538#post306538

**Comment by tomaae** [comment]
yea, I already joined the conversation there

**Comment by tomaae** [comment]
OMV6 is now supported in version 1.3.0
