### ISSUE TITLE
[Question] After a couple of hours, I get 401 errors and no more data

### ISSUE THREAD

**Issue by Smiggel** [tomaae/homeassistant-openmediavault#78]
I have been testing the plugin for a while now. I noticed that after every few hours, the add-on stops working and is no longer able to receive data. I see this is my HA logs:

> Logger: custom_components.openmediavault.omv_api
> Source: custom_components/openmediavault/omv_api.py:301 
> Integration: OpenMediaVault (documentation, issues) 
> First occurred: 16 april 2022 22:11:23 (13 occurrences) 
> Last logged: 00:22:26
> 
> OpenMediaVault 192.168.0.50 unable to fetch data (401)

I am wondering if I have to do some special setting in OMV or HA. At a restart of HA it works for a couple of hours and then it suddenly stops.

**Comment by tomaae** [comment]
I'm afraid I cant help you much here. 401 means OMV is refusing connection with authorization error, this is not a normal behavior.
maybe you can try to remove .omv_cookies file and reauthorize the integration, but that should not be the issue.

**Comment by Smiggel** [comment]
Hmmm ok. My NAS is still running and the account is also still accessible. It's not blocked or anything. Really don't understand what the issue.

However, as soon as it happens, the script also stops working. Was hoping it could run again after it failed, but it doesn't do that.

**Comment by Smiggel** [comment]
Deleted the file. Rebooted HA assistant. It worked then for 30 minutes and then stopped working again. Sometimes it works for hours before it stops. No idea what is going on.

**Comment by tomaae** [comment]
your best bet may be omv logs. not sure if access issues are logged tho

**Comment by mcsurl** [comment]
Im also getting the OpenMediaVault 10.0.0.13 unable to fetch data (401) error. OMV still working fine and can still access. FWIW, I only started getting this error after last HA update, 

As with OP its intermittent.

**Comment by tomaae** [comment]
Did you deleted the file?

**Comment by Smiggel** [comment]
@tomaae Nope. I tried it, but did not help. I set up an extra OMV setup. Simple install with harddisk attached. Added it to HA as a second installation to monitor. 

The plugin fetched the data nicely for over 36 hours and then suddenly died... NAS is still running and accessible. No clue why is suddenly stopped. Same error too as with my main OMV installation.

**Comment by tomaae** [comment]
you should check OMV logs to find anything relevant. I dont think we can find something from HA side, as that is OMV returning the error.
also, which OMV version is that?

**Comment by Smiggel** [comment]
Can't find anything strange in the logs. No errors or what so ever.

Both my OMV installations run on: 6.0.22-1 (Shaitan)

**Comment by RaptorPR443** [comment]
> Can't find anything strange in the logs. No errors or what so ever.
> 
> Both my OMV installations run on: 6.0.22-1 (Shaitan)
> 
> [EDIT] Strange this is, that when I restart HA and the plugin loads, that it works for a while again. So, to be honest, I don't think it has anything to do with the NAS, as I do not need to restart the NAS to make it work again.

i have the same issue as you but with OMV5. Same thing, works for a while and the drops, sometimes comes back up after an hour or so or it does not. i started getting the error after last update from integration. i will roll back and post results.

**Comment by Kad-litox** [comment]
Same problem, only load data of the plugin first minutes after rebooting the docker.
OMV 6.0.27-1 (Shaitan) 
Portainer 2.13.1 
Home Assistant Core 2022.5.5

All the log errors like this:
[error log.txt](https://github.com/tomaae/homeassistant-openmediavault/files/8809910/error.log.txt)

**Comment by Smiggel** [comment]
Still having the same issue too.

It started since OMV 6. On OMV 5 I did. It have this problem.

The moment it stops working is also completely random. Sometimes it works for a day. Other moments it stops after a hour or few hours. 🤷‍♂️

**Comment by BebeMischa** [comment]
Just for a different angle of view, my instance does work fine, latest HA and up to date OMV 6. Never seen this problem in the past too.
So the issue affect a lot op people, but not everyone.
I'm open for questions, if someone needs to compare his settings with mine ;-)

**Comment by Smiggel** [comment]
Do you use a separate account or your admin account?

Do you have any extra settings set, so that you perhaps can handle more requests?

**Comment by BebeMischa** [comment]
Using admin account, no additional settings made.

**Comment by BebeMischa** [comment]
First difference spotted, i run OMV on a intel i5  machine, as also my HA is an intel Celeron machine. No rPi's involved here.

**Comment by thumsj138** [comment]
> First difference spotted, i run OMV on a intel i5 machine, as also my HA is an intel Celeron machine. No rPi's involved here.

I run OMV and HA on the same machine (intel i3)

**Comment by tomaae** [comment]
it is a difficult one, since I'm not able reproduce it.
I could try to create some crazy debug version if someone is willing to work closely with me on this. But be warned, it may be a lot of manual file replacing and testing.

**Comment by Smiggel** [comment]
If I can access the files somewhere, I could give it a try. Not sure where everything is stored.

**Comment by martonperei** [comment]
Happening here too. I think it happens because of the session timeout in OMV. I have it set to 60 minutes and the error happens every hour on the dot, and I have the following messages in the server log:

`Jun 03 01:16:53 nas openmediavault-webgui[2508012]: Authorized login from 172.18.0.9 [username=admin, user-agent=python-requests/2.27.1]`

So I think the session expires when the query happens, then it reconnects fine in the next query. Should be an easy fix to try to reconnect on 401, if that doesn't work, then rethrow the error.

**Comment by Smiggel** [comment]
> Happening here too. Though for me, the plugin works mostly fine apart from intermittent errors. I think it happens because of the session timeout in OMV. I have it set to 60 minutes and the error happens every hour on the dot, and I have the following messages in the server log:
> 
> `Jun 03 01:16:53 nas openmediavault-webgui[2508012]: Authorized login from 172.18.0.9 [username=admin, user-agent=python-requests/2.27.1]`
> 
> So the session expires when the query happens, then it reconnects fine in the next query. Should be an easy fix to try to reconnect on 401, if that doesn't work, then rethrow the error.
> 
> I've disabled the session timeout for now, to see if it still happens.

Where do you disable the session timeout?

**Comment by martonperei** [comment]
> Where do you disable the session timeout?

System -> Workbench -> "Auto logout"

**Comment by Smiggel** [comment]
> > Where do you disable the session timeout?
> 
> System -> Workbench -> "Auto logout"
> 
> No 401 errors since I've disabled it.

Thanks. I disabled it just now. See how that will go. :-)

**Comment by thumsj138** [comment]
> Happening here too. Though for me, the plugin works mostly fine apart from intermittent errors. I think it happens because of the session timeout in OMV. I have it set to 60 minutes and the error happens every hour on the dot, and I have the following messages in the server log:
> 
> `Jun 03 01:16:53 nas openmediavault-webgui[2508012]: Authorized login from 172.18.0.9 [username=admin, user-agent=python-requests/2.27.1]`
> 
> So the session expires when the query happens, then it reconnects fine in the next query. Should be an easy fix to try to reconnect on 401, if that doesn't work, then rethrow the error.
> 
> I've disabled the session timeout for now, to see if it still happens.


Thanks a lot for this solution... It is perfect now... I disabled the session timeout and all work fine :-)



> I'm afraid I cant help you much here. 401 means OMV is refusing connection with authorization error, [...].

Yes You were right

**Comment by Smiggel** [comment]
> Happening here too. Though for me, the plugin works mostly fine apart from intermittent errors. I think it happens because of the session timeout in OMV. I have it set to 60 minutes and the error happens every hour on the dot, and I have the following messages in the server log:
> 
> `Jun 03 01:16:53 nas openmediavault-webgui[2508012]: Authorized login from 172.18.0.9 [username=admin, user-agent=python-requests/2.27.1]`
> 
> So the session expires when the query happens, then it reconnects fine in the next query. Should be an easy fix to try to reconnect on 401, if that doesn't work, then rethrow the error.
> 
> I've disabled the session timeout for now, to see if it still happens.

So far so good. Timeout seemed to been have te problem. It’s still stable for now.

**Comment by tomaae** [comment]
thats interesting, may be worth reporting to omv developers.
sessions should not time out since it is accessed every minute. since it affects only some people, its most likely a bug and not some intentional change.

**Comment by Smiggel** [comment]
Still up and running here. Since the timeout is off, it’s running fine. No issue here anymore. 🤞

**Comment by martonperei** [comment]
> thats interesting, may be worth reporting to omv developers.
> sessions should not time out since it is accessed every minute. since it affects only some people, its most likely a bug and not some intentional change.

It looks like OMV uses `updatelastacces` to reset the timeout on each API call, which is set to False in `omv_api.py:249`. (It should be enabled by default if you omit the option)

**Comment by tomaae** [comment]
> > thats interesting, may be worth reporting to omv developers.
> > sessions should not time out since it is accessed every minute. since it affects only some people, its most likely a bug and not some intentional change.
> 
> It looks like OMV uses `updatelastacces` to reset the timeout on each API call, which is set to False in `omv_api.py:249`. (It should be enabled by default if you omit the option)
> 
> Edit: Omitting the option seems to work. There's still an initial 401 if I set the timeout to 1 minute (probably connects on startup, then only makes the first query after the timeout when home assistant is finished starting up?) so I think the reconnect on 401 is still needed to fully fix it.

Changed in master, can you test it?
Would be weird imo, but worth a try.
It should reconnect, I will have to test reconnection.

**Comment by martonperei** [comment]
Yeah, the change in master works too.

Seems like the `#Api error` path is not reached because it's handled as a socket error.
This is what's returned for a 401:

`{'response': None, 'error': {'code': 0, 'message': 'Session expired.', 'trace': 'OMV\\HttpErrorException: Session expired. in /usr/share/php/openmediavault/session.inc:157\nStack trace:\n#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(68): OMV\\Session->validateTimeout()\n#1 /var/www/openmediavault/rpc.php(45): OMV\\Rpc\\Proxy\\Json->handle()\n#2 {main}'}}`

So we need to check for session expiry in the socket error path too.
