### ISSUE TITLE
[Bug] Integration not found after installing from HACS

### ISSUE THREAD

**Issue by jokke-ilujo** [tomaae/homeassistant-openmediavault#79]
## Describe the issue
I just don't seem to be able to access the integration.

## How to reproduce the issue
1. Install the repository via HACS
2. Reboot HA
3. Go to Integrations page
4. Click Add Integration
5. search for "Open|OpenMedia|OpenMediaVault" or any part of it
6. The integration does not show up

## Expected behavior
Setup screen to provide IP and credentials to my OMV deployment.

## Software versions
 - Home Assistant version: HA 2022.5.5
 - openmediavault integration version: 1.3.0
 - openmediavault software version: 5.6.26-1 (Usul)

## Traceback/Error logs
  Logs are clean

**Comment by tomaae** [comment]
that happens with HACS sometimes. clear you browser cache.

**Comment by jokke-ilujo** [comment]
Indeed, thanks!
