### ISSUE TITLE
Suuport HA Integrations icons

### ISSUE THREAD

**Issue by LanceMcCarthy** [tomaae/homeassistant-openmediavault#8]
HA has added support for icons and logos in the Integrations page.  This HACS integration does not have the new icons.

Screenshots:

Here's the Add Integration list, filtered:

![image](https://user-images.githubusercontent.com/3520532/80920225-5c0afe80-8d3c-11ea-9687-554e29c17297.png)

Here's the Integrations page card

![image](https://user-images.githubusercontent.com/3520532/80920336-24508680-8d3d-11ea-804a-df49874691dd.png)

## Describe the solution you'd like

It is a simple fix and only requires two image files. since this integration is not a part of the out of the box Supervisor, the solution should still be the same as long as the images are copied to the correct locaiton.

Details here https://github.com/home-assistant/brands

**Comment by LanceMcCarthy** [comment]
I'm closing this because I just learned that HA doesn't support icons for custom integrations.

**Comment by Marte2007** [comment]
It does support them now (https://github.com/home-assistant/brands/commit/0a7b99096c66518dfefe05fe7a0d1a9f7f16da67), you can submit a pull request to have them added.

**Comment by tomaae** [comment]
great, I have created PR for it already
