### ISSUE TITLE
[Bug] The integration fails when trying to get S.M.A.R.T info for bcache device

### ISSUE THREAD

**Issue by jokke-ilujo** [tomaae/homeassistant-openmediavault#80]
## Describe the issue
OMV returns 500 on the S.M.A.R.T call on bcache device. This causes all entities to be reported as "Unknown".

## How to reproduce the issue
1. Create bcache (F.E. /dev/bcache0) device on the OMV
2. Enable OMV HASS integration
3. The integration starts logging "unable to fetch data (500)" (from omv_api.py:301)
4. OMV reports "POST /rpc.php HTTP/1.1" 500 829 "-" "python-requests/2.27.1"
5. OMV integration manages to create only 3 devices OMV ['Disk', 'Filesystem', 'System']

## Expected behavior
Skip bcache as it's non-smart capable device and move on.

## Software versions

 - Home Assistant version: HA 2022.5.5
 - openmediavault integration version: v1.3.0
 - openmediavault software version: v5.6.26-1

**Comment by tomaae** [comment]
merged, thanks
