### ISSUE TITLE
Unavailable every minute

### ISSUE THREAD

**Issue by Xitro01** [tomaae/homeassistant-openmediavault#85]
Almost every minute it shows that the entities are not available, as can be seen here:
![Knipsel](https://user-images.githubusercontent.com/19844787/184084758-e69e1b65-f656-4652-9334-5dd9234f7590.PNG)
Is this normal behaviour?

**Comment by tomaae** [comment]
try installing master, there has been some updates that may help this

**Comment by BebeMischa** [comment]
I had this too, the only way to get rid of it was changing settings in the UI of OMV.

System -> Workbench -> Auto logout -> Disable.

Now everything is normal.

**Comment by Xitro01** [comment]
Master solved my issue!
