### ISSUE TITLE
sensor for CPU and GPU temperature

### ISSUE THREAD

**Issue by lecrams** [tomaae/homeassistant-openmediavault#86]
With all the high temperature of the last time it would be usefull to have sensors for the CPU and GPU temperature

**Comment by tomaae** [comment]
does OMV provide such temperatures?

**Comment by lecrams** [comment]
I have an odroid XU4 with cloudshell and on the display of the cloudshell it shows both the temperatures so there is a way of retrieve them or to calculate. Maybe ask the omv developer?

**Comment by lecrams** [comment]
I asked the OMV forum and they came up with this:
The cputemp plugin uses /sys and lm-sensors. Maybe you could use those?

**Comment by tomaae** [comment]
this integration is based on omv api, there is no access to os itself.
if ther is a 3rd plugin which shows those data in omv ui, it is technically possible, but right now this integration does not have support for 3rd party omv plugins.

**Comment by lecrams** [comment]
Then it can not be done I guess unfortunately. Then I have to find an other easy way to get an alarm when my NAS get overheated

**Comment by tomaae** [comment]
I suggest using SNMP. You can get that working natively in HA.
