### ISSUE TITLE
Permission level/requirements to fetch information from OMV

### ISSUE THREAD

**Issue by Pistol-Peet** [tomaae/homeassistant-openmediavault#87]
Good day everyone,

Reading the documentation I have not seen any hint on recommended settings to enable monitoring information to be fetched.
My questions are:
- What is the setting requirement on the OMV instance? (eg. Does monitoring need to be enabled for this plugin to get info?)
- What is the best practice setting for the HA-Plugin?
- As I don´t want to use the/any admin account for this service, what permission level does a separate account need to be able to read the details? (I am still browsing OMV documentation, as I sense it should mention somewhere. If you know, I´d appreciate a hint)

Thank you for working out this plugin!
I´ve been looking for this for a long time.

Best.
Pistol-Peet

**Comment by tomaae** [comment]
you need admin permissions. its hard coded in omv api.
