### ISSUE TITLE
[Feature] Option to add different port number instead of default port 80

### ISSUE THREAD

**Issue by Smiggel** [tomaae/homeassistant-openmediavault#90]
## Is your feature request related to a problem? Please describe.
I have set my OMV default admin port number to 5001. I tried adding the url with the port number in OMV like: 192.168.1.10:5001. I get most of my devices. So it sees the installation and retrieves the info. However, I see a lot of error logs with "No response".
For some reason the port number is not always used.

## Describe the solution you'd like
I would like to see an extra field for the port number during the setup. Default value would be 80. The default value should be adjustable.

## Describe alternatives you've considered
Add the port number in the url. Like described above. Like: 192.168.1.10:5001. However, an extra field would be more clear to users.

**Comment by tomaae** [comment]
Port definition works fine within host field, additional field dedicated to port is not necessary. Port is always used, so that is not the issue.
You will need to debug the integration to find more information.

**Comment by tomaae** [comment]
https://github.com/tomaae/homeassistant-openmediavault#enabling-debug

**Comment by Smiggel** [comment]
Logs don't show anything extra except for what I posted above here.

**Comment by Smiggel** [comment]
It seems that the problem as resolved itself. The errors suddenly don't show anymore. I assume it has to do with a reboot of the system.
