### ISSUE TITLE
[Bug] OMV integration not listed even after clearing cache

### ISSUE THREAD

**Issue by mortee** [tomaae/homeassistant-openmediavault#93]
## Describe the issue
Installed the custom component, but OMV isn't listed in the Add Integration pop-up menu.

## How to reproduce the issue
On HA 2022.11.3 Docker install and configure HACS, add HACS integrtion, restart everything, clear browser cache, and observe OpenMediaVault missing from the Integrations menu.

Checked from the Android client app too, with the same result.

## Expected behavior
It should be there, ready to be added.

## Software versions
 - Home Assistant version: HA 2022.11.3 Docker
 - openmediavault integration version: -
 - openmediavault software version: 6.0.46-5

## Diagnostics data
Found absolutely nothing relevant in the logs.

**Comment by tomaae** [comment]
I'm afraid that I cant help you much there, since this is on HA side. Only known fix is deleting browser cache, I'm not awere about any other problem that may affect HA integration list.

**Comment by mortee** [comment]
Is there a way to simply verify what HACS actually brings to the table?

**Comment by tomaae** [comment]
Not sure, but I dont think thats something HACS does. HA pulls custom integrations from folder even without HACS.

**Comment by mortee** [comment]
Sorry for my ignorance, but if HA is supposed to pull custom integrations from some "folder" (not sure what you mean by that), then why is HACS even needed to install OMV?

**Comment by BebeMischa** [comment]
HACS puts them automatically in the right folder, so that even with less computer knowledge the jobs get done right. But that's not the only benefit. HACS does also check, if the integration is OK.

**Comment by mortee** [comment]
I'm sorry, it was really my ignorance. Somehow I assumed the HACS integrations would appear in the same menu as the builtin ones. 

In any case, maybe the readme might mention that OMV can be installed by simply cloning the custom_components/homeassistant folder into the HA directory.

**Comment by tomaae** [comment]
Yea, HACS is just install and update manager. It is a great convinience tool.
Copying/cloning files manually is a default way to add new integrations. thats how you install HACS after all. 
But installing custom components manually comes with lot of potential issues which are better avoided. HACS is kind of "must have" tool.
