### ISSUE TITLE
CPU temperature

### ISSUE THREAD

**Issue by slakouz** [tomaae/homeassistant-openmediavault#94]
Please add CPU temperature monitoring if possible. Usually OVM installed in NAS hardware. HA sits in other hardware.

**Comment by tomaae** [comment]
I dont think OMV provides such data. Is it available anywhere?

**Comment by slakouz** [comment]
openmediavault-cputemp plugin doing this

**Comment by BebeMischa** [comment]
Then you are one of the lucky guys... Here it always shows 23.8 C :-)

**Comment by slakouz** [comment]
Here is how I getting same result by ssh integration, but this integration is buggy and not under maintenance some years:
`   command: 'cat /sys/class/thermal/thermal_zone0/temp'
   value_template: "{{ ( value.split('\r\n')[1] | multiply(0.001)) | round(1) }}"
`

**Comment by tomaae** [comment]
this integration does not support plugins, only main OMV
