### ISSUE TITLE
Integration stopped working today

### ISSUE THREAD

**Issue by DerEmder** [tomaae/homeassistant-openmediavault#95]
Hi

The integration only shows _unavailable_ this evening for all entities. Sometimes it changes to real values for a second then _unavailable_ again.

I restarted everything already - no change.

Please advise

Screenshot:

![Bildschirmfoto vom 2023-01-11 19-16-10](https://user-images.githubusercontent.com/91392202/211923005-9a8fcffa-23ac-4cac-bddc-d52c609c2471.jpg)

### System-Info:

System: **Self-Made NAS**
Controller: **Rock Pi 64 with SATA-Hat**
OS: **Armbian Linux 5.15.80-rockchip64**
Software: **Open Media Vault 6.1.4-2**

**Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest**

**Hard Disks:**

1 x WDC WD80EDAZ-11TA3A0 (8TB)
2 x ST16000NM001G-2KK103 (Seagate Exos 16TB)
1 x WDC WD80EZAZ-11TDBA0 (8TB)
1 x ST8000AS0002-1NA17Z (Archive 8TB)
1 x Samsung SSD 840 EVO (250GB)

**Comment by DerEmder** [comment]
I love these kind of answers :)

Of course that's what I did immediately. And no - there was no log entry about your integration - nothing, nada, nix. I had a look into the full system log as well as the logbook. As I said - no entry whatsoever.

Could it be that your software gets confused if one or more drives are in standby and some are not? (Just grasping the straws here because the integration worked fine yesterday.) Between yesterday (working) and today (not working) is only that I put two of my drives into standby after 30 minutes (which they did) and three drives are left running 24/7.

**Comment by tomaae** [comment]
Yea well, you somehow managed to bypass standard template and didnt said you checked the logs. So I cant know ;) You would be surprised how many people ignore logs with clear messages.

Havent seen a case where there was nothing in log.
Only option is to run integration in debug then. Lets see what we can find out.
Also, what is your integration version?

**Comment by DerEmder** [comment]
> You would be surprised how many people ignore logs with clear messages.

I am not suprised easily anymore. I am in IT since 1983/1984 so I know how ignorant people can be :)
 
> Havent seen a case where there was nothing in log. Only option is to run integration in debug then. Lets see what we can find out. Also, what is your integration version?

Let me try something else first. I removed the integration completely and will re-install it. Btw, it was version 1.3.0 installed via HACS.

**Comment by BenGinders** [comment]
I have only installed the add-on yesterday so not sure on long term stability, however I have noticed similar symtoms where all sensors show "Unknown".  On checking the logs I can see 102 occurances of the same error as can be seen in the logs.
![Screenshot_20230112_180038_Home Assistant.png](https://user-images.githubusercontent.com/80892912/212144541-c3e995f6-e58f-451b-b3ef-6ad1ff660384.png)

**Comment by jes1417** [comment]
I also see these regularly.

'''
This error originated from a custom integration.

Logger: custom_components.openmediavault.omv_api
Source: custom_components/openmediavault/omv_api.py:301
Integration: OpenMediaVault (documentation, issues)
First occurred: January 10, 2023 at 3:04:46 PM (45 occurrences)
Last logged: 11:46:49 AM

OpenMediaVault 10.30.46.200:8090 unable to fetch data (401)
'''

**Comment by tomaae** [comment]
> I have only installed the add-on yesterday so not sure on long term stability, however I have noticed similar symtoms where all sensors show "Unknown". On checking the logs I can see 102 occurances of the same error as can be seen in the logs. ![Screenshot_20230112_180038_Home Assistant.png](https://user-images.githubusercontent.com/80892912/212144541-c3e995f6-e58f-451b-b3ef-6ad1ff660384.png)



> I also see these regularly.
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.openmediavault.omv_api
> Source: custom_components/openmediavault/omv_api.py:301
> Integration: OpenMediaVault (documentation, issues)
> First occurred: January 10, 2023 at 3:04:46 PM (45 occurrences)
> Last logged: 11:46:49 AM
> 
> OpenMediaVault 10.30.46.200:8090 unable to fetch data (401)
> ```

Those are different, as you actually get error.
Error 401 from API means unauthorized. If your credentials are correct, try changing integration version to "master" in hacs.

**Comment by BenGinders** [comment]
I know I have the correct credentials as I sometimes see values from the integration.

I have just installed the master branch amd will feedback if I see any occurances.
![Screenshot_20230112_185940_Home Assistant.png](https://user-images.githubusercontent.com/80892912/212157588-1f9c3849-ed2f-47e4-8d89-eea34f0680a6.png)

**Comment by DerEmder** [comment]
Okay, installed 1.3.0 again. As expected it shows all values. I'll have a close look at it and will report any error messages the integration spits out (or any misbehauviour)

**Comment by DerEmder** [comment]
Additional information:

As soon as I reboot OMV your integration shows "unavailable" followed by correct values once in a while. Now I also got the same error as above in my logs:

OpenMediaVault 10.42.0.2 unable to fetch data (401)
OpenMediaVault 10.42.0.2 unable to fetch data (500) 

If I restart HA then everything seems fine again.

**Comment by tomaae** [comment]
may be same as others had. try installing master version using hacs
