### ISSUE TITLE
[Bug] Too many failed login attempts messages

### ISSUE THREAD

**Issue by kdw2060** [tomaae/homeassistant-openmediavault#96]
## Describe the issue
The integration itself works. I can set it up without issues and the sensors work.
However I get bombarded by warning e-mails from OMV telling me my user has been banned after too much failed login attempts. Which is odd off course because the integration works, ergo succeeds in establishing the connection.

## Software versions
 - Home Assistant version: 2023.1.4
 - openmediavault integration version: 1.3.0
 - openmediavault software version: 6.1.4-2 (Shaitan)

**Comment by tomaae** [comment]
Check HA log for error messages.

**Comment by kdw2060** [comment]
There were no error messages there. In the mean time I solved the issue with a tip I read from another user. It is necessary to change the setting 'Auto logout' in the workbench to 'disabled'. Maybe you can add that information to the integration's documentation?

**Comment by tomaae** [comment]
that issue is already solved in master
