### ISSUE TITLE
Updates no longer reported

### ISSUE THREAD

**Issue by Smiggel** [tomaae/homeassistant-openmediavault#97]
I noticed that when there is an update for OMV, this is no longer detected by the plugin.

It seems something has changed in OMV, that prevents this from working.

**Comment by tomaae** [comment]
Which version?

**Comment by Smiggel** [comment]
I run OMV 6.1.6-2 (Shaitan)

And the plug-in release is 1.3.0.

**Comment by BebeMischa** [comment]
Just checked, same here.

Version
6.1.4-1 (Shaitan)
Processor
Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz
Kernel
Linux 6.0.0-0.deb11.2-amd64

**Comment by ralphy7** [comment]
I have noticed the same issue.

Version
6.1.4-2 (Shaitan)

Integration release 1.3.0

**Comment by querys1** [comment]
I have the issue, that I cannot connect. "No response from host" when I try to login.
![omv](https://user-images.githubusercontent.com/116440848/214262086-1f28ab63-8f75-401f-890d-4f54351352b6.jpg)

I can ping OMV with the Terminal-function of HA.

**Comment by casinick** [comment]
Hello, i have noticed the same issue.

Version
6.3.0-1 (Shaitan)

Integration release 1.3.0

**Comment by bluemantwo** [comment]
Same here.  

6.3.4-1 (Shaitan)
Integration release v1.3.0
