### ISSUE TITLE
[Feature] - Add port selector

### ISSUE THREAD

**Issue by StanislavJochman** [tomaae/homeassistant-openmediavault#99]
Hi I am trying to connect plugin to my OMV, but realised that port can not be specified. It works for most users but in OMV port can be changed.

Best regards
Stanislav Jochman

**Comment by tomaae** [comment]
you can change port. just specify ip:port in integration setup

**Comment by StanislavJochman** [comment]
Oh ok did not know that. Thanks for quick reply.
